### ISSUE TITLE
Código IBGE do município

### ISSUE THREAD

**Issue by leogregianin** [cuducos/minha-receita#114]
O código do município devolvido pela API é um código chamado "TOM", que possui 4 dígitos e, aparentemente, é um padrão interno da SERPRO. [Neste link](http://www.fazenda.mg.gov.br/governo/assuntos_municipais/codigomunicipio/codmunicoutest_sp.html) encontrei uma referência a isto.

Com a finalidade de padronizar a cidade com código IBGE e facilitar a integração, poderíamos criar um arquivo com a referência do código TOM em relação ao código IBGE e expor, também, o código IBGE do município na API?

**Comment by cuducos** [comment]
Seria uma belíssima ideia! E digo belíssima pois normalmente sou contra “mudar” os dados da Receita Federal — para manter a integridade, transparência e consistência do projeto. Mas adicionar camadas de dados pode enriquecer muito.

**Comment by cuducos** [comment]
Se ajudar: https://github.com/cuducos/brazilian-cities

**Comment by leogregianin** [comment]
Acredito as APIs do IBGE não ajudam pois não temos nelas o código TOM. 
Imaginei um json estático com código TOM e Código IBGE como no exemplo abaixo (nem precisaria do nome).
Ao rodar o `transform`, faz a leitura do json e adiciona o novo campo `codigo_ibge`.

```json
[
    {
        "ibge": 5300108,
        "tom": 9701,
        "nome": "Brasília",
    },
    {
        "ibge": 3550308,
        "tom": 7107,
        "nome": "São Paulo",
    },
    (...)
]
```

**Comment by cuducos** [comment]
Eu penso diferente, pois o desafio é ponto é fazer o mapemento do nome, mais UF para o código do IBGE. Hoje temos o nome e a UF nos dados da Receita Federal, então precisamos carregar em memória algo como:

```csv
nome,uf,codigo_ibge
Brasília,DF,5300108
```

E ter algo que faça:

```go
func cityIBGECode(name, state string) string
```


Podemos carregar em memó

**Comment by leogregianin** [comment]
Nós já temos o `codigo_municipio` nos dados da Receita Federal, então poderíamos carregar em memória algo como:

```
codigo_municipio,codigo_ibge
9701,5300108
```

E ter algo que faça:

```go
func cityIBGECode(codigo_municipio int) int
```

Trabalhando com o tipo inteiro na entrada e na saída não teremos preocupações em normalizar nomes e, teoricamente, a conversão será mais rápida.

**Comment by athossampayo** [comment]
Tentando agregar a discussão:
Acredito que a sugestão do @leogregianin seria mais certeira e mais rápida. Poderia ser usado alguma fonte da relação TOM-SERPRO / IBGE como essa: [tomweb](https://www.tomweb.receita.fazenda.gov.br/TomWeb/municipio/consultarMunicipioPorCodigoNome.jsf)

Inclusive, se for o caso, posso fazer um scraping rápido do site para termos um json com as relações e disponibilizar.

**Comment by cuducos** [comment]
Gente, eu estou perdido.

> O código do município devolvido pela API é um código chamado "TOM", que possui 4 dígitos e, aparentemente, é um padrão interno da SERPRO.

De qual API estamos falando? Da Minha Receita? Imaginei que sim

> poderíamos criar um arquivo com a referência do código TOM em relação ao código IBGE

Eu prefiro incluir na resposta da Minha Receita ambos os códigos, usando uma [tabela de _look up_ do código de município faltante no enriquecimento dos dados](https://github.com/cuducos/minha-receita/blob/main/CONTRIBUTING.md#estrat%C3%A9gia).

Assim a resosta seria, por exemplo:

```json
{
    …
    "codigo_municipio": 9701,
    "codigo_municipio_inge": 5300108,
    "municipio": "BRASILIA",
    …
}
```

Por isso acho que o que precisamos é uma fonte que tenha os códigos do IBGE, ou IBGE **e** TOM.

> Acredito as APIs do IBGE não ajudam pois não temos nelas o código TOM.

Discordo, pois podemos mapear normalizando nome do município e UF, e os dados viriam de uma fonta oficial.

> Inclusive, se for o caso, posso fazer um scraping rápido do site para termos um json com as relações e disponibilizar.

Isso funcionária apenas como protótipo. A ideia aqui é trabalhar sempre com os dados direto da fonte, então isso teria que ser construído a cada vez que rodamos o ETL. E por isso volto ao meu comentário inicial:

* No ETL temos o nome do município, a UF
* No [JSON do IBGE](https://servicodados.ibge.gov.br/api/v1/localidades/aniversarios) temos o nome do município, a UF e o código do IBGE
 

> Imaginei um json estático com código TOM e Código IBGE como no exemplo

Seria o ideal, mas ele existe? Se ele não existe, com criamos um?

A mesma pergunta faço para essa afirmação aqui:

> Nós já temos o `codigo_municipio` nos dados da Receita Federal, então poderíamos carregar em memória algo como:
>
> ```csv
> codigo_municipio,codigo_ibge
> 9701,5300108
> ```

Essa tabela/mapeanto existe já? Se não existe, como criamos uma?

> Acredito que a sugestão do @leogregianin seria mais certeira e mais rápida

Concordo, só não entendo de onde vem a relação de códigos IBGE-TOM. `https://www.tomweb.receita.fazenda.gov.br/TomWeb/municipio/consultarMunicipioPorCodigoNome.jsf` seria legal pela descrição, por ter os dois códigos, mas ela não abre com problema de segurança — não sei se é temporário.

**Comment by cuducos** [comment]
(desculpem abrir e fechar a _issue_ acidentalmente **duas** vezes; sou uma anta mesmo e esbarro no _trackpad_ hahaha…)

**Comment by cuducos** [comment]
Complementando com um pseudo-código: https://gist.github.com/cuducos/aee3b7e78dd33aa51aa50bc7a08961f1

**Comment by leogregianin** [comment]
> Gente, eu estou perdido.

Não está perdido não :D

Sim, estamos falando da API da minha-receita.

Também gosto da ideia de incluir ambos os códigos, já temos o `codigo_municipio` e o nome do município, precisamos acrescentar o `codigo_municipio_ibge`.

Não consegui nenhuma fonte oficial que tenha os dois códigos juntos, por isso, como os códigos TOM e o código IBGE do município nunca mudarão (acredito), imaginei em construir um arquivo json estático e deixá-lo dentro do projeto com a seguinte relação:

```json
[
   {
      ...
      "9701": 5300108
      ...
   }
]
```

Só estou tentando simplificar o processo, mas se a regra é sempre buscar uma fonte externa oficial não há problemas em buscar pelo nome e uf do município.

**Comment by cuducos** [comment]
Peguei aquele pseudo código que rascunhei de manhã e evoluí ele para esse rascunho: #116

O que esse código faz atualmente? Dado que [o arquivo `.zip` do IBGE disponível nessa página](https://ibge.gov.br/explica/codigos-dos-municipios.php) exista localmente, ele:
* Descompacta o arquivo
* Encontra o arquivo Excel relevante
* Lê esse Excel e cria a estrutura de dados do _lookup_ para que o método `lookupIBGE.cityIBGECode(name, state string) string` funcione

Marquei no PR o que eu lembro que falta para o PR sair do estado de _rascunho_ — se quiserem continuar, mandem PQ para aquela _branch_, senão vou evoluindo no tempo livre aqui.

**Comment by cuducos** [comment]
E… [deu ruim](https://github.com/cuducos/minha-receita/pull/116#issuecomment-1043848845) : (

**Comment by cuducos** [comment]
Amanhã vou tentar estudar [essa tabela do Tesouro Transparente](https://www.tesourotransparente.gov.br/ckan/dataset/abb968cb-3710-4f85-89cf-875c91b9c7f6/resource/eebb3bc6-9eea-4496-8bcf-304f33155282/download/TABMUN.CSV) como alternativa

**Comment by cuducos** [comment]
Foi! PR pronto para revisão : )

**Comment by leogregianin** [comment]
Já imaginava que a busca por nome de cidade iria ter problemas : ) [muito bom](https://github.com/cuducos/minha-receita/blob/f78c8c1cfc760e6178ee9cf6ded438d1eb161aea/transform/cities.go#L32).

**Comment by leogregianin** [comment]
Só para deixar claro e documentado sobre o código do IBGE. Esse [JSON do IBGE](https://servicodados.ibge.gov.br/api/v1/localidades/aniversarios) retorna o código com 6 dígitos, ou seja, sem o dígito verificador. E a [tabela do Tesouro Transparente](https://www.tesourotransparente.gov.br/ckan/dataset/abb968cb-3710-4f85-89cf-875c91b9c7f6/resource/eebb3bc6-9eea-4496-8bcf-304f33155282/download/TABMUN.CSV) retorna com 7 dígitos. Prefiro o retorno com os 7 dígitos mesmo :D

**Comment by cuducos** [comment]
Não seria melhor o de 7 para atingir um público maior?
Vc pode fazer um _slice_ na leitura, mas quem precisa dos 7 dígitos ficaria sem ter como “adivinhar” o 7º dígito…
Ou tem algum caso de uso que posso estar menosprezando?

**Comment by leogregianin** [comment]
> Não seria melhor o de 7 para atingir um público maior?

Concordo totalmente.

> Prefiro o retorno com os 7 dígitos mesmo :D

Foi o que eu disse logo acima :D

Melhor o código completo com 7 dígitos e não como o IBGE devolve.

**Comment by rossanodr** [comment]
Oi pessoal, desculpem ressuscitar esse issue. Estou precisando identificar o código TOM  das cidades, pois o webservice da minha cidade pede isso. Vi esse issue e parecia que iria se enquadrar, porém entrando no site da minhareceita.org eu entendi que as buscas só são feitas por cnpj, correto? Não existe uma busca pela cidade?

**Comment by cuducos** [comment]
> Não existe uma busca pela cidade?

Existe, mas [como documentado](https://docs.minhareceita.org/faq/#como-buscar-por-cnae-uf-etc) não é parte da API.
