### ISSUE TITLE
Como iniciar o uso do projeto? `go.mod file not found`

### ISSUE THREAD

**Issue by reichaves** [cuducos/minha-receita#118]
Em um computador com Ubuntu eu instalei o Go e depois o postgresql - nunca usei eles
Parti das orientações aqui - https://docs.minhareceita.org/instalacao/

No terminal depois tentei isso:

```console
$ go get
go: go.mod file not found in current directory or any parent directory; see 'go help modules'
```

Por favor, eu preciso instalar mais algo? Ou fazer outra configuração?

**Comment by cuducos** [comment]
OI @reichaves — sempre bom ver gente iniciando no projeto 💜 

Editei sua mensagem um pouco para facilitar a leitura (formatação de saídas do terminal, por exemplo) e para deixar o título mais específico, ok? Espero que não se incomode!

**Hipóteses**

O erro que você está tendo diz que não existe um arquivo `go.mod` no diretório onde você executou o `go get`. Penso em duas possibilidades que podem levar a isso:

* Você clonou o código fonte do projeto?
* Depois de clonar, você entrou no diretório do código fonte do projeto?

Digo isso pois, ao contrário do que diz o erro, [existe um `go.mod` na raíz do projeto](https://github.com/cuducos/minha-receita/blob/main/go.mod), então algum desses passos você deve ter pulado.

**Sugestões**

* Você pode clonar o repositório com `git clone https://github.com/cuducos/minha-receita.git`
* Você pode ver o diretório onde você está com o comando `pwd` — e esse tem que ser o diretório do projeto.

**Exemplo**

No meu caso eu faria algo assim:

```console
$ pwd
/home/cuducos/
$ git clone https://github.com/cuducos/minha-receita.git  # talvez você não tenha feito isso
…
$ cd minha-receita  # talvez você tenha esquecido desse passo aqui
$ pwd
/home/cuducos/minha-receita
$ go get
…
```

---

Faz sentido?

Se fizer, como você acha que [a página de instalação](https://github.com/cuducos/minha-receita/blob/main/docs/instalacao.md) poderia ser melhorada? Fique à vontade para mandar um PR, ou comentar aqui, melhorando a redação dela :)

**Comment by reichaves** [comment]
Olá 
Muito obrigado

Não tinha entendido que precisava fazer o clone

Fiz isso e fui no diretório dos arquivos e digitei

go get 

Deu certo instalou vários itens:
go: downloading github.com/spf13/cobra v1.3.0
go: downloading github.com/cuducos/go-cnpj v0.0.1
go: downloading github.com/go-pg/pg/v10 v10.10.6
....

Mas depois deu erro:

go build -o /usr/local/bin minha-receita
package minha-receita is not in GOROOT (/usr/local/go/src/minha-receita)

**Comment by cuducos** [comment]
Me parece que o comando documentado está errado 🤦

Tente `go build -o /usr/local/bin/minha-receita main.go`

(estou digitando do celular, não testei)

**Comment by reichaves** [comment]
Funcionou aqui, com o sudo su

Agora vou tentar entender como usar

**Comment by reichaves** [comment]
É possível, por exemplo, baixar dois CSVs com a base inteira da Receita? Assim:
1 - Um CSV com um CNPJ por linha, com dados básicos da empresa - com key o CNPJ

2 - Um CSV com os sócios de cada empresa em cada linha, então o mesmo CNPJ pode se repetir nas linhas - depende do número de sócios. Aqui as chaves seriam o CNPJ, mas também depois para orientação o nome completo dos sócios e o CPF mascarado

**Comment by ramolec** [comment]
> Funcionou aqui, com o sudo su
> 
> Agora vou tentar entender como usar

Eu sou newbie, to iniciando o projeto, você teve que instalar o go novamente no sudo su?

Aqui eu tive o seguinte erro tentando rodar sem sudo su

> go build command-line-arguments: copying /tmp/go-build3527935269/b001/exe/a.out: open /usr/local/bin/minha-receita: permission denied

**Comment by reichaves** [comment]
> > Funcionou aqui, com o sudo su
> > Agora vou tentar entender como usar
> 
> Eu sou newbie, to iniciando o projeto, você teve que instalar o go novamente no sudo su?
> 
> Aqui eu tive o seguinte erro tentando rodar sem sudo su
> 
> ` go build command-line-arguments: copying /tmp/go-build3527935269/b001/exe/a.out: open /usr/local/bin/minha-receita: permission denied`

Não precisei reinstalar
Mas no Linux, pelo menos aqui, para executar esse último comando (go build -o /usr/local/bin/minha-receita main.go), eu tive que entrar no super usuário, o sudo su (https://mateusmuller.me/2019/01/30/sudo-o-que-e-sudo-su-no-linux/)
Os comandos anteriores não - é importante também criar o PATH

**Comment by cuducos** [comment]
> Funcionou aqui, com o sudo su

Isso provavelmente pois você escolheu criar o binário em `/usr/local/bin` e tua configuração de usuário não te dá permissão para escrever nesse diretório. O Minha Receita **não** precisa do `sudo`, @reichaves.

> `go build command-line-arguments: copying /tmp/go-build3527935269/b001/exe/a.out: open /usr/local/bin/minha-receita: permission denied`

Esse `exe` me faz pensar que talvez tu esteja no Windows, @ramolec. `-o /usr/local/bin/minha-receita` diz que o binário (o _output_) vai ser criado no diretório `/usr/local/bin/minha-receita` — o que é um diretório inválido no Windows. Troque isso por um diretório válido e veja se funciona.

**Comment by cuducos** [comment]
@reichaves, sobre tua dúvida do CSV, foge do tópico dessa _issue_, então abri outra e te marquei.

@ramolec, se o erro persistir, foge do tópico dessa _issue_, mas fique à vontade para abrir uma _issue_ com teu erro específico, ok?
