### ISSUE TITLE
Incluir descrição do motivo de situação cadastral

### ISSUE THREAD

**Issue by cuducos** [cuducos/minha-receita#12]
Podemos importar [dessa planilha](https://receita.economia.gov.br/orientacao/tributaria/cadastros/cadastro-nacional-de-pessoas-juridicas-cnpj/DominiosMotivoSituaoCadastral.csv), linkada aqui: https://receita.economia.gov.br/orientacao/tributaria/cadastros/cadastro-nacional-de-pessoas-juridicas-cnpj/dados-publicos-cnpj

**Comment by mtrentz** [comment]
Bom dia.

Eu não sei mexer em Go então não consigo fazer isso para você. Mas tenho aqui o insert statement em SQL dessas tabelas de consulta que estão como open issue no momento que estou usando para ter um output com as descricoes completas.

Se isso for util para você posso te enviar eles.

**Comment by cuducos** [comment]
Acho que a questão dessa _issue_ é mais sobre automatizar esse processo no ETL (_extract, transform, load_) do que ter acesso aos dados mesmo. De qualquer forma, pode compartilhar aqui sim, pois isso é parte da _issue_ e ajuda!

**Comment by mtrentz** [comment]
Sim entendo, eu fiz isso exatamente só pra ter como output as descrições direto do query mesmo. Sem precisar ficar fazendo as ligações depois. Segue os comandos: 
```
CREATE TABLE motivo_situacao_cadastral (
    codigo INT PRIMARY KEY,
    descricao TEXT NOT NULL
);

INSERT INTO motivo_situacao_cadastral (codigo, descricao)
    VALUES (1, 'EXTINÇÃO POR ENCERRAMENTO LIQUIDAÇÃO VOLUNTÁRIA'), (2, 'INCORPORAÇÃO'), (3, 'FUSÃO'), (4, 'CISÃO TOTAL'), (5, 'ENCERRAMENTO DA FALÊNCIA'), (6, 'ENCERRAMENTO DA LIQUIDAÇÃO'), (7, 'ELEVAÇÃO A MATRIZ'), (8, 'TRANSPASSE'), (9, 'NÃO INÍCIO DE ATIVIDADE'), (10, 'EXTINÇÃO PELO ENCERRAMENTO DA LIQUIDAÇÃO JUDICIAL'), (11, 'ANULAÇÃO POR MULTICIPLIDADE'), (12, 'ANULAÇÃO ONLINE DE OFICIO'), (13, 'OMISSA CONTUMAZ'), (14, 'OMISSA NÃO LOCALIZADA'), (15, 'INEXISTENTE DE FATO'), (16, 'ANULAÇÃO POR VÍCIOS'), (17, 'BAIXA INICIADA E AINDA NÃO DEFERIDA'), (18, 'INTERRUPÇÃO TEMPORÁRIA DAS ATIVIDADES'), (19, 'OMISSO DE DIRPJ ATÉ 5 EXERCÍCIOS'), (20, 'EM CONDIÇÃO DE INAPTIDÃO'), (21, 'PEDIDO DE BAIXA INDEFERIDA'), (22, 'RESTABELECIMENTO COM CERTIDÃO POSITIVA COM EFEITO DE NEGATIVA'), (23, 'COM PENDÊNCIA FISCAL'), (24, 'POR EMISSÃO CERTIDÃO NEGATIVA'), (25, 'CERTIDÃO POSITIVA COM EFEITO DE NEGATIVA'), (26, 'IRREGULARIDADE DE PAGAMENTO'), (27, 'IRREGULARIDADE DE RECOLHIMENTO E EXIGIBILIDADE SUSPENSA'), (28, 'TRANSFERÊNCIA FILIAL CONDIÇÃO MATRIZ'), (29, 'AGUARDANDO CONF. DE DIRPJ/DIPJ'), (30, 'ANR - AGUARDANDO CONF. DE DIRPJ/DIPJ'), (31, 'EXTINÇÃO DA FILIAL'), (32, 'INEXISTENTE DE FATO – ADE/COSAR'), (33, 'TRANSFERÊNCIA DO ÓRGÃO LOCAL A CONDIÇÃO DE FILIAL DO ÓRGÃO REGIONAL'), (34, 'ANULAÇÃO DE INSCRIÇÃO INDEVIDA'), (35, 'EMPRESA ESTRANGEIRA AGUARDANDO DOCUMENTAÇÃO'), (36, 'PRÁTICA IRREGULAR DE OPERAÇÃO DE COMERCIO EXTERIOR'), (37, 'BAIXA DE PRODUTOR RURAL'), (38, 'BAIXA DEFERIDA PELA RFB AGUARDANDO ANALISE DO CONVENENTE'), (39, 'BAIXA DEFERIDA PELA RFB E INDEFERIDA PELO CONVENENTE'), (40, 'BAIXA INDEFERIDA PELA RFB E AGUARDANDO ANALISE DO CONVENENTE'), (41, 'BAIXA INDEFERIDA PELA RFB E DEFERIDA PELO CONVENENTE'), (42, 'BAIXA INDEFERIDA PELA RFB E SEFIN, AGUARDANDO ANALISE SEFAZ'), (43, 'BAIXA DEFERIDA PELA RFB, AGUARDANDO ANALISE DA SEFAZ E INDEFERIDA PELA SEFIN'), (44, 'BAIXA DEFERIDA PELA RFB E SEFAZ, AGUARDANDO ANALISE SEFIN'), (45, 'BAIXA DEFERIDA PELA RFB, AGUARDANDO ANALISE DA SEFIN E INDEFERIDA PELA SEFAZ'), (46, 'BAIXA DEFERIDA PELA RFB E SEFAZ E INDEFERIDA PELA SEFIN'), (47, 'BAIXA DEFERIDA PELA RFB E SEFIN E INDEFERIDA PELA SEFAZ'), (48, 'BAIXA INDEFERIDA PELA RFB, AGUARDANDO ANALISE SEFAZ E DEFERIDA PELA SEFIN'), (49, 'BAIXA INDEFERIDA PELA RFB, AGUARDANDO ANALISE DA SEFAZ E INDEFERIDA PELA SEFIN'), (50, 'BAIXA INDEFERIDA PELA RFB, DEFERIDA PELA SEFAZ E AGUARDANDO ANALISE DA SEFIN'), (51, 'BAIXA INDEFERIDA PELA RFB E SEFAZ, AGUARDANDO ANALISE DA SEFIN'), (52, 'BAIXA INDEFERIDA PELA RFB, DEFERIDA PELA SEFAZ E INDEFERIDA PELA SEFIN'), (53, 'BAIXA INDEFERIDA PELA RFB E SEFAZ E DEFERIDA PELA SEFIN'), (54, 'BAIXA - TRATAMENTO DIFERENCIADO DADO AS ME E EPP (LEI COMPLEMENTAR NUMERO 123/2006)'), (55, 'DEFERIDO PELO CONVENENTE, AGUARDANDO ANALISE DA RFB'), (60, 'ARTIGO 30, VI, DA IN 748/2007'), (61, 'INDICIO INTERPOS. FRAUDULENTA'), (62, 'FALTA DE PLURALIDADE DE SOCIOS'), (63, 'OMISSÃO DE DECLARAÇÕES'), (64, 'LOCALIZAÇÃO DESCONHECIDA'), (66, 'INAPTIDÃO'), (67, 'REGISTRO CANCELADO'), (70, 'ANULAÇÃO POR NÃO CONFIRMADO ATO DE REGISTRO DO MEI NA JUNTA COMERCIAL'), (71, 'INAPTIDÃO (LEI 11.941/2009 ART.54)'), (72, 'DETERMINAÇÃO JUDICIAL'), (73, 'OMISSÃO CONTUMAZ'), (74, 'INCONSISTÊNCIA CADASTRAL'), (80, 'BAIXA REGISTRADA NA JUNTA, INDEFERIDA NA RFB');
```

**Comment by cuducos** [comment]
Oi @andidevel,

Muito obrigado pela mensagem! No entanto, como a Receita Federal mudou o formato dos dados, e como isso levou a uma grande restruturação do código (andamento registrado em #37), não acho que seja a melhor hora para contribuir pois quase tudo é reescrito do zero : (

Quando eu avançar mais um passo na lista de tarefas da #37 teremos um modelo de dados mais estável e aí sim fica mais fácil contribuir. Se vc puder esperar mais um pouco, agradeço demais : )

**Comment by andidevel** [comment]
Desculpe! Agora que vi em detalhes a issue #37. Se você quiser, posso ajudar nessa refatoração também.

**Comment by andidevel** [comment]
@cuducos,

> Quando ele ficar pronto, ele vai ser a base do _refactor_, então acho que a partir dali vai ficar fácil de chegar cotribuindo!

Legal! Vou ficar de olho no desenvolvimento então, e esperar esse item ficar pronto.

Neste meio tempo, tentei rodar o branch dev aqui, para já ir entendendo o software. Os testes em "download" falharam, não terminando de "buildar" o container. Aparentemente os testes estão consultando a página oficial, e me parece que o nome dos arquivos mudam de acordo com a data de atualização dos dados (foi um padrão que eu acho que encontrei, mas pode ser só uma coincidência), então a parte ".D1XXXX." do nome do arquivo, atualmente é ".D10911.", sendo que a data de atualização está "11/09/2021". Isso faz os testes falharem, pois os nomes dos arquivos esperados estão com ".D10710." (provavelmente quando foram atualizados em 10/07/2021). Vou checar novamente na próxima atualização para saber se a minha hipótese se confirma.

Fiz umas pequenas alterações nos testes, que estão no meu fork [1], que talvez faça sentido para você. E talvez seja melhor transferir a discussão para uma outra issue/canal, se você achar mais apropriado, :-).

Valeu!

[1] https://github.com/andidevel/minha-receita/tree/dev

**Comment by cuducos** [comment]
> Aparentemente os testes estão consultando a página oficial, e me parece que o nome dos arquivos mudam de acordo com a data de atualização dos dados

Na verdade, não era para acessar o site oficial, era para [ler](https://github.com/cuducos/minha-receita/blob/d8cb1bb22bbe0daeb921eed58580096fd2d4581d/download/download_test.go#L233-L246) o [HTML do `testdata/`](https://github.com/cuducos/minha-receita/blob/dev/testdata/dados-publicos-cnpj.html).

Se isso não está acontecendo, pode abrir uma issue para a gente conversar sobre isso : )

**Comment by cuducos** [comment]
Fechado em favor da #37
