### ISSUE TITLE
Frequência de atualização

### ISSUE THREAD

**Issue by galodoidobsb** [cuducos/minha-receita#131]
Bom dia!
Gostaria de saber se há uma frequência de atualização da base de dados no servidor, já que a Receita atualiza a base trimestralmente.
Há algum lugar onde podemos visualizar a informação sobre a data de atualização dos dados consultados?

**Comment by cuducos** [comment]
> Há algum lugar onde podemos visualizar a informação sobre a data de atualização dos dados consultados?

A ideia é ter, mas está em andamento ainda. Você pode acompanhar na _issue_ #93.

> Gostaria de saber se há uma frequência de atualização da base de dados no servidor, já que a Receita atualiza a base trimestralmente.

Normalmente assim que reparo que tem um novo lote, eu tento fazer a atualização. Esse último não consegui fazer pois maio foi um mês complicado para mim, e nas três vezes que tentei, a conexão caiu no meio do processo (acontece). Então essa ainda estou devendo.

**Comment by cuducos** [comment]
Vocês tem uma ideia para [fazer o processo de atualização mais fácil ou estável](https://twitter.com/cuducos/status/1537051701735305216?s=21&t=85tfwI5nXDv4R9DQHWmp9Q)?
