### ISSUE TITLE
Incluir alerta sobre qualidade de dados públicos

### ISSUE THREAD

**Issue by jedibruno** [cuducos/minha-receita#143]
Nossa experiência mostra que nem sempre bases de dados públicos estão imunes a problemas. Dados podem estar desatualizados, incorretos, incompletos ou simplesmente estranhos. Alertar o usuário pode ser importante, não só para fins de transparência e usabilidade como também para coletar esses problemas e requerer correções/melhorias na fonte:

**Sugestões:**

1. Incluir alerta de que dados públicos não necessariamente pode estar corretos;

2. Criar canal (email, etc) para pessoas mandarem alertas sobre entradas incorretas ou estranhas;

**Comment by cuducos** [comment]
Fechado por #144
