### ISSUE TITLE
Fazer com que o comando `sample` copie o arquivo `updated_at.txt` caso ele exista

### ISSUE THREAD

**Issue by cuducos** [cuducos/minha-receita#152]

**Comment by eu-ovictor** [comment]
Gostaria de contribuir nessa issue, poderia me dar um pouco mais de contexto sobre ela por favor?

**Comment by cuducos** [comment]
Só para saber por onde começar… o que você entende e o que você  não entende dessa _issue_?

Alguns links:
* [O que é o comando `sample`](https://github.com/cuducos/minha-receita/blob/main/CONTRIBUTING.md#amostra-dos-arquivos-para-testes)
* [O que é o arquivo `updated_at.txt`](https://github.com/cuducos/minha-receita/issues/93)

O caso de uso seria mais ou menos o seguinte:
1. baixei todos os dados e quero testar o ETL (ou seja, `$ minha-receita transform`) mas não quero carregar todos os dados (por exemplo, quero testar se o processo funciona, e não necessariamente criar um banco de dados completo)
2. para isso, antes o comando `sample`
3. Se faço isso, e executo o `transform -d diretório-que-usei-no-sample` vai dar erro pois não existe o `updated_at.txt` no `diretório-que-usei-no-sample`

É esse erro que o PR que fecha essa _issue_ deve evitar.

**Comment by eu-ovictor** [comment]
No caso de não existir o arquivo `updated_at.txt ` no diretório de origem do `sample` a app deveria criar um com o valor _mockado_ para ser usado no `transform`? Ou deve apenas ignorar?

**Comment by cuducos** [comment]
Bela perguinta! Não tinha pesando nisso…

Pensando alto aqui:
* se tem o arquivo, o processo só vai
* se não tem o arquivo, o processo pode só mostrar uma mensagem nos logs `log.Output(2, fmt.Sprintf("updated.txt file not found in %s", dir))`
* se não tem, mas a pessoa usou a opção `--mock-updated-at`, aí sim ele cria um arquivo com alguma data _mockada_

O que acha?

**Comment by eu-ovictor** [comment]
Acho uma boa. Para a opção `--mock-updated-at` a gente poderia permitir a pessoa passar uma data como argumento, e usar a data do dia atual como valor default, no formato `aaaa-mm-dd` que é como ele criado no download. O que acha?

**Comment by cuducos** [comment]
Perfeito : )
