### ISSUE TITLE
Possibilidade de pausar e recomeçar o download

### ISSUE THREAD

**Issue by cuducos** [cuducos/minha-receita#161]
Creio que podemos criar uma funcionalidade que guarda o status do download para que possa ser reiniciado posteriormente.

O download fatia cada arquivo em `n` partes, que são baixadas isoladamente. Por exemplo, se o `--chunk-size` for 512, ao baixar uma arquivo `foobar.zip` de 2kb,  isso resulta em três downloads de 512b, mais um de 464.

Vamos supor que em uma tentativa de download, a primeira e a terceira fatias foram concluídas, e as demias ou falharam ou o processo foi interrompido antes que elas fossem concluídas. Isso poderia ser salvo em um arquivo assim:

```json
{
    "chunkSize": 512,
    "files": {
        "foobar.zip": [true, false, true, false]
    }
}
```

Ou podemos até utilizar um formato padrão mais enxuto (e assim fica fácil de fazer um _parser_ sem ter que se preocupar em JSON _marshalling_):

```
512
foobar.zip:1010
```

Esse arquivo pode ficar no diretório de download, e ser excluído quando o download encerra com sucesso. Uma opção `--restart` no comando de download pode excluí-lo também.

Ao iniciar um download, se antes de enfileirar as fatias para download, caso esse arquivo exista e o `--chunk-size` seja o mesmo, podemos verificar se é ou não necessário baixar cada fatia.

**Comment by eu-ovictor** [comment]
Quando vamos baixar pela primeira vez o arquivo é criado com o valor default de 0 para todas as fatias?

**Comment by cuducos** [comment]
> Quando vamos baixar pela primeira vez o arquivo é criado com o valor default de 0 para todas as fatias?

[Sim](https://github.com/cuducos/minha-receita/blob/ae7cdb042dd6043b4e65480991b8018badce94de/download/recover.go#L113) : )
