### ISSUE TITLE
Corrigir CSV gerado pelo Go

### ISSUE THREAD

**Issue by cuducos** [cuducos/minha-receita#17]
Na _branch_ [`go`](https://github.com/cuducos/minha-receita/tree/go) o CSV gerado contém erros que quebram a importação pelo Postgres.

**Como reproduzir**

1. `docker-compose up -d postgres` (ou inicie o PostgreSQL da maneira que preferir)
1. Crie uma variável de ambiente `POSTGRES_URI` com as crdenciais do PostgreSQL (por exemplo, `postgres://minhareceita:minhareceita@localhost:5432/minhareceita?sslmode=disable`)
1. `go run main.go drop` (caso o banco de dados já exista e tenha dados, vamos limpar e começar do zero)
1. `go run main.go create`
1. `go run main.go download` (sugiro usar o `--mirror`)
1. `go run main.go parse`

Isso vai gerar os arquivos `data/empresa.csv.gz` e `data/socio.csv.gz` (entre outros), mas o PostgreSQL não consegue importar esses dois arquivos. O comando `import` não mostra erros, mas manualmente é possível verificá-los:

```console
$ gunzip -c data/empresa.csv.gz | psql $POSTGRES_URI -c "\copy public.empresas FROM STDIN DELIMITER ',' CSV HEADER;"
ERROR:  invalid byte sequence for encoding "UTF8": 0xc2 0x4e
CONTEXT:  COPY empresas, line 1793
$ gunzip -c data/socio.csv.gz | psql $POSTGRES_URI -c "\copy public.socios FROM STDIN DELIMITER ',' CSV HEADER;"
ERROR:  invalid byte sequence for encoding "UTF8": 0xc7 0xd5
CONTEXT:  COPY socios, line 12174
```

**Critérios de aceitação**

- [ ] O comando `import` mostra os error do PostgreSQL (ao invés de falhar silenciosamente)
- [ ] O comando `import` importa os dados do arquivo `empresa.csv.gz`
- [ ] O comando `import` importa os dados do arquivo `socio.csv.gz`

**Ideias**

Penso em implementar um novo comando, `validate` para validar os CSVs criados. Podemos usar, por exemplo, o [`tableschema`](https://github.com/frictionlessdata/tableschema-go) e adicionar o esquema dos dados em um diretório `schemas`. Creio que isso dá mais segurança sobre os resultados do `parse` e ajude a debugar o que está errado nos CSVs.

**Comment by vagnerdev** [comment]
Acho uma ótima ideia criar um _validate_.

**Comment by cuducos** [comment]
Feito, @vagnerdev, não sei se tu chegou a ver os últimos _commits_. Não foi feito um comando `validate`, mas um [método `validate`](https://github.com/cuducos/minha-receita/blob/a1910707b0e386a0f9f5b8b76c0b40a81449da1e/transform/parsers.go#L219-L252) que valida cada linha ao gerar o CSV.

Aproveitando, essa _issue_ foi fechada pelo d8afe26 , mas ca7f4151dc987e0065a33ca8c6833887f56293e3, ae2a14ebe759ec4a6cbae5299a7dc4e86b192fbc, e a1910707b0e386a0f9f5b8b76c0b40a81449da1e complementaram!
