### ISSUE TITLE
Estou com problemas para captar alguns dados

### ISSUE THREAD

**Issue by carlosmixz** [cuducos/minha-receita#180]
Minhareceita.org está com dados de 2022-11-24, mas no dropbox parece que tem muito mais atualizados, o site vai deixar de ser atualizado?

minhareceita.org/updated: {"message":"2022-11-24 é a data de extração dos dados pela Receita Federal."}

**Comment by cuducos** [comment]
> site vai deixar de ser atualizado?

Não.
Mais detalhes em #175
