### ISSUE TITLE
Erro ao executar `main.exe create` localmente - Windows 

### ISSUE THREAD

**Issue by renato4012** [cuducos/minha-receita#182]
Sou novo em programação e estou enfrentando um problema ao executar o comando "./main.exe create" localmente .

Quando tento executar o comando para criar as tabelas do banco de dados, recebo o seguinte erro:

```
`PS D:\minha-receita> ./main.exe create
Error: could not load the sql templates: error parsing &{postgres/create.sql CREATE UNLOGGED TABLE IF NOT EXISTS {{ .CompanyTableFullName }} (
    {{ .IDFieldName }}   bigint NOT NULL,
    {{ .JSONFieldName }} jsonb NOT NULL
);
CREATE TABLE IF NOT EXISTS {{ .MetaTableFullName }} (
    {{ .KeyFieldName }}   char(16) NOT NULL PRIMARY KEY,
    {{ .ValueFieldName }} text NOT NULL
)
 �D�♫�→-{v‼☺áԻ�} template: template: pattern matches no files: `postgres\create.sql
Usage:
  minha-receita create [flags]

Flags:
  -u, --database-uri string      PostgreSQL URI (default DATABASE_URL environment variable)
  -h, --help                     help for create
  -s, --postgres-schema string   PostgreSQL schema (default "public")

could not load the sql templates: error parsing &{postgres/create.sql CREATE UNLOGGED TABLE IF NOT EXISTS {{ .CompanyTableFullName }} (
    {{ .IDFieldName }}   bigint NOT NULL,
    {{ .JSONFieldName }} jsonb NOT NULL
);
CREATE TABLE IF NOT EXISTS {{ .MetaTableFullName }} (
    {{ .KeyFieldName }}   char(16) NOT NULL PRIMARY KEY,
    {{ .ValueFieldName }} text NOT NULL
)
 �D�♫�→-{v‼☺áԻ�} template: template: pattern matches no files: `postgres\create.sql`
```

Eu segui o tutorial disponível  e verifiquei se o Go está instalado corretamente. Compilei o projeto sem problemas, mas ao tentar criar as tabelas do banco de dados usando o comando "./main.exe create", esse erro ocorre.

go version go1.20.5 windows/amd64
psql (PostgreSQL) 15.3
Windows 10

Gostaria de solicitar a ajuda da comunidade para entender a causa desse erro e obter orientações sobre como resolvê-lo ao executar o projeto localmente.

Qualquer ajuda seria muito apreciada. Obrigado!

**Comment by cuducos** [comment]
Curioso… não tenho Windows aqui para tentar reproduzir o erro, mas vi que o erro é causado na chamada do [`embed.ParseFS`](https://github.com/cuducos/minha-receita/blob/8c87d1d0fe0e4a8f325c5da9cc86822e2e10baf3/db/postgres.go#L52) ([nativo do Go](https://pkg.go.dev/text/template#ParseFS)). Vi também que o caminho para o arquivo está sendo construído corretamente (pois a barra aparece invertida para você, e normal para mim no Linux a macOS).

Uma coisa que me deixou curioso foi esse trecho que aparece ao fim do conteúdo do template: `�D�♫�→-{v‼☺áԻ�} `.

Você sabe o que é isso?

Será que esse arquivo (`db/postgres/create.sql`) foi acidentalmente editado?

Qual o resultado de `git status` e `git diff`?

**Comment by cuducos** [comment]
Você pode testar uma mudança no código?


https://github.com/cuducos/minha-receita/blob/8c87d1d0fe0e4a8f325c5da9cc86822e2e10baf3/db/postgres.go#L52

*Talvez* a API dos _templates_ não diferencie barra de barra invertida dependendo do sistema operacional, o que faria essa linha ter que ser, na verdade:

```go
 t, err := template.ParseFS(sql, filepath.Join("postgres/" + f.Name())) 
```

É só um **chute** mas preciso de alguém com Windows (ou mais conhecimento de Go) para confirmar : )

**Comment by renato4012** [comment]
```
PS D:\minha-receita> git status
On branch main
Your branch is up to date with 'origin/main'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   db/postgres.go

Untracked files:
  (use "git add <file>..." to include in what will be committed)
        main.exe
        postgres.go
        postgres/
        postgres_test.go

no changes added to commit (use "git add" and/or "git commit -a")

PS D:\minha-receita> git diff db/postgres/create.sql
PS D:\minha-receita>
```



Modifiquei o código conforme a sugestão, mas o erro persiste. Em relação aos caracteres especiais, pode ser um problema de codificação (apenas uma suposição), mas, honestamente, não tenho certeza.

**Comment by cuducos** [comment]
Você se importa em compartilhar o resutado de `git diff` (não `git diff db/postgres/create.sql`)?

**Comment by cuducos** [comment]
Ah! E obrigado por testar meu chute : ) Pena que foi um chute errado hahaha…

**Comment by renato4012** [comment]
```
PS D:\minha-receita> git diff
warning: in the working copy of 'go.mod', LF will be replaced by CRLF the next time Git touches it
diff --git a/db/postgres.go b/db/postgres.go
index ffa3af4..fdbf833 100644
--- a/db/postgres.go
+++ b/db/postgres.go
@@ -49,7 +49,7 @@ func (p *PostgreSQL) loadTemplates() error {
                return fmt.Errorf("error looking for templates: %w", err)
        }
        for _, f := range ls {
-               t, err := template.ParseFS(sql, filepath.Join("postgres", f.Name()))
+               t, err := template.ParseFS(sql, "postgres/" + f.Name())
                if err != nil {
                        return fmt.Errorf("error parsing %s template: %w", f, err)
                }
PS D:\minha-receita>
```


Segue o resultado do `git diff`. 

Adendo: Outros comandos como  `./main.exe updated-at` ele funciona normal.
```
 PS D:\minha-receita> ./main.exe updated-at
2023-05-18
```

**Comment by cuducos** [comment]
Apenas para registro: tentei converter o arquivo `create.sql` para outros _encodings_ ver se gerava alguma diferença e o `git diff` fica limpo — ou seja, dificilmente é algo de _encoding_. Tentei gerando o conteúdo com:

```console
$ iconv -f UTF-8 -t ISO-8859-1 db/postgres/create.sql
$ iconv -f UTF-8 -t ASCII db/postgres/create.sql
```

(e, claro!, salvando os resiltados)

**Comment by cuducos** [comment]
Outra pergunta simples. Vi que você usou `./main.exe create` no teu exemplo. Você recompilou o `main.exe` quando fez as mudanças, né? Vez ou outra eu mesmo esqueço. Uma opção é usar o `go run main.go create` enquanto estamos testando coisas, só para garantir…

**Comment by renato4012** [comment]
Deu certo o go `run main.go create`
```
PS D:\minha-receita> go run main.go create
2023/06/14 14:51:46 Creating table public.cnpj…
```

Agora estou executando o `go run main.go transform`

```
PS D:\minha-receita> go run main.go transform
2023/06/14 14:57:02 Saving the updated at date to the database…
2023/06/14 14:57:02 Loading Simples files…
2023/06/14 14:57:02 Loading Empresas files…
2023/06/14 14:57:02 Loading Socios files…
Processing base CNPJ, partners and taxes   3% |█                                              | (3934722/111780811, 100657 it/s) [44s:17m51s]

```

Quando concluir aviso! Muito obrigado por ora.

**Comment by cuducos** [comment]
Perfeito! E teu arquivo estava assim quando você rodou `go run main.go create`, confere?

```diff
--- a/db/postgres.go
+++ b/db/postgres.go
@@ -49,7 +49,7 @@ func (p *PostgreSQL) loadTemplates() error {
                return fmt.Errorf("error looking for templates: %w", err)
        }
        for _, f := range ls {
-               t, err := template.ParseFS(sql, filepath.Join("postgres", f.Name()))
+               t, err := template.ParseFS(sql, "postgres/" + f.Name())
```

Isso pode ser um PR, se quiser contribuir?

**Comment by renato4012** [comment]
Sim, mantive a sua sugestão de alteração.

Creio que nao tenho "maturidade" para fazer um PR. rsrs

**Comment by cuducos** [comment]
Muito obrigado por trazer o _bug_ para cá e ajudar na resolução. Estou acertando uns detalhes do #183 e isso vai ser uma bela melhoria para o projeto — e tem muito de ti nisso!
