### ISSUE TITLE
[Dúvida] Download do banco de dados completo

### ISSUE THREAD

**Issue by gersonmachado** [cuducos/minha-receita#184]
Bom dia!
Meu nome é Gerson, sou estudante de Análise e Desenvolvimento de Sistemas. Beleza?
Espero que esteja tudo bem fazer esse tipo de pergunta por aqui, estou seguindo as orientações que deixou na sua API.

Estou mergulhando agora em Análise de Dados e me deparei com essa dificuldade de acesso ao BD de CNPJs da Receita.. Gostaria então de fazer o download da base completa para realizar minhas pesquisas localmente com python/pandas. É aqui a minha dúvida..

Como eu posso fazer isso com aqueles arquivos separados no link <https://mirror.minhareceita.org/>?

Peço compreensão pois é minha primeira vez lidando com uma base de dados grande.
Obrigado!

**Comment by cuducos** [comment]
Oi @gersonmachado,

Naquela pasta compartilhada deico dois tipos de arquivos:

- Os executáveis que são, basicamente, esse programa que criei chamado _Minha Receita_; esses são os arquivos `minha-receita-*`
- Uma cópia dos dados que baixo da Receita Federal utilizando o _Minha Receita_; essas são as pastas com formato de data ano-mês-dia (por exemplo, o mais recente é `2023-05-18`)

Ou seja, se quer baixar os dados mais atuais, é só entrar nesse diretório, baixar os arquivos que estão lá, descompactar e terá os CSV que podes ler com o Pandas, por exemplo. No site oficial da Receita Federal tem um PDF chamado _layout_ que documenta o que tem em cada arquivo.

Ajudei ou só repeti o que já sabia?

**Comment by gersonmachado** [comment]
Opa, ajudou bastante!
Eu desconfiava que seria somente a pasta mais recente, mas preferi te fazer uma consulta antes para tirar essa dúvida e prosseguir.

Agora vou me virar aqui pra organizar essa tabela com o auxílio esse Layout. 
Obrigado pela atenção Eduardo!
