### ISSUE TITLE
Etapa transform sempre trava nos 53%

### ISSUE THREAD

**Issue by wandersonsousa** [cuducos/minha-receita#185]
Estou usando o banco de dados do dockercompose minha-receita, porém ele nunca consegue finalizar a primeira etapa que é: Processing base CNPJ, partners and taxes.

Já tentei diversos comandos, a últimas tentativa foi da seguinte forma:
`docker-compose run --rm minha-receita transform -d /mnt/data/ --no-privacy --max-parallel-db-queries=1 --batch-size=1024`                                    

Minha máquina:
MacBook Pro (16 polegadas, 2021)
processador: Apple M1 Max
ram: 32 GB
1TB

**Comment by cuducos** [comment]
Alguns detalhes para a gente entender melhor:

* Quanto espaço livre em disco? (o comando `df -h /` deve ajudar)
* Quais as configurações da instância do Docker? Isso normalmente se configura no Docker Desktop (eu acho), pode ser que tenha pouca memória dedicada ao Docker
* Qual a data de divulgação pela Receita Federal dos dados que você está processando?

[Não costumo utilzar o Docker para os dados completos.](https://github.com/cuducos/minha-receita/issues/176#issuecomment-1425887166) Apenas mantenho para facilitar os testes e desenvolvimento. Se puder testar _sem_ o Docker, pode ser uma boa ; )

**Comment by wandersonsousa** [comment]
> 

Tenho cerca de 800GB disponível. Estou processando os últimos dados da receita. Sobre a questão de configurar os limites de armazenamento do docker, creio que seja o problema, vou testar e retorno com o resultado, em caso de o resultado ser negativo, vou testar sem o docker

**Comment by carlsonwf** [comment]
Relatei um problema que pode ser relacionado (ou não).

https://github.com/cuducos/minha-receita/issues/189#issue-1814712983

Estou testando a importação de uma base mais antiga... De qualquer forma, @wandersonsousa, coloque aí os logs do postgres e da própria aplicação pra gente tentar entender melhor o que passa.

**Comment by carlsonwf** [comment]
Tentei a importação com os dados de 15/01/2023.

Log do postgres:

```
2023-07-20 17:49:29.058 -03 [14880] ERROR:  invalid byte sequence for encoding "UTF8": 0x00
2023-07-20 17:49:29.058 -03 [14880] CONTEXT:  COPY cnpj, line 6545, column json
2023-07-20 17:49:29.058 -03 [14880] STATEMENT:  copy "cnpj" ( "id", "json" ) from stdin binary;
2023-07-20 17:49:29.801 -03 [8868] ERROR:  invalid byte sequence for encoding "UTF8": 0x00
2023-07-20 17:49:29.801 -03 [8868] CONTEXT:  COPY cnpj, line 7620, column json
2023-07-20 17:49:29.801 -03 [8868] STATEMENT:  copy "cnpj" ( "id", "json" ) from stdin binary;
2023-07-20 17:49:30.098 -03 [9312] LOG:  could not receive data from client: An existing connection was forcibly closed by the remote host.

```

Log no console
```
Processing base CNPJ, partners and taxes 100% |█████████████████████████████████████████████████████████████| (108762489/108762489, 68926 it/s)
2023/07/20 17:42:27 Loading Estabelecimentos files…
Creating the JSON data for each CNPJ   9% |█████                                                            | (5308416/55155262, 22246 it/s) [6m26s:37m20s]panic: send on closed channel

goroutine 73620684 [running]:
```

**Comment by cuducos** [comment]
> Estou testando a importação de uma base mais antiga

Qual exatamente?

Você pode também verificar os pontos que mencionei [anteriormente](https://github.com/cuducos/minha-receita/issues/185#issuecomment-1610174566)? Isso ajuda muito a eu te ajudar…

**Comment by carlsonwf** [comment]
> > Estou testando a importação de uma base mais antiga
> 
> Qual exatamente?
> 
> Você pode também verificar os pontos que mencionei [anteriormente](https://github.com/cuducos/minha-receita/issues/185#issuecomment-1610174566)? Isso ajuda muito a eu te ajudar…

Foi mal. Base de 15/01/2023. Estou tentando agora com a de 17/12/2022.

To com 35gb livre e nao estou usando docker, fiz o build do app

**Comment by cuducos** [comment]
> To com 35gb livre

É [pouco](https://docs.minhareceita.org/instalacao/#requisitos).

**Comment by cuducos** [comment]
O erro que você está tendo (_ An existing connection was forcibly closed by the remote host_) também pode indicar sobrecarga nos recursos computacionais como CPU e memória, [segundo esse artigo](https://techcommunity.microsoft.com/t5/azure-database-for-postgresql/troubleshoot-postgresql-an-existing-connection-was-forcibly/ba-p/925164).

**Comment by ralexsander** [comment]
Testando no Mac M1 aqui travou em 58%, provavelmente foi por espaço em disco disponível para o container, pois a transformação usa bastante espaço no /tmp também... ao rodar nativamente deu certo

**Comment by cuducos** [comment]
> pois a transformação usa bastante espaço no `/tmp` também

Sim. Só para corroborar essa afirmação: os 108 milhões de registros de base do CNPJ, sócios e dados fiscais são carregados em um banco de dados de chave/valor (é a parte _Processing base CNPJ, partners and taxes_). E é [no diretório temporário que esse banco de dados fica](https://github.com/cuducos/minha-receita/blob/b2988d6ec7615e9f0f6ae21ee6cfb9851e4b86ac/transform/kv.go#L184).

Estou processando os dados de julho agora, está em 27% e esse diretório já tem 3Gb:

```console
$ du -hd1 /tmp | grep minha
3.0G	/tmp/minha-receita-badger-1661591632
```

Com certeza ele passa dos 10Gb (pois muito dado ainda está em memória, já que o Badger faz essas artimanhas para poder ser rápido na escrita).

**Comment by carlsonwf** [comment]
Eu provisionei uma maquina com 16gb de RAM e 250GB de espaço livre. Deu certo.

Provavelmente o problema tenha sido o espaço em disco, mas não pensei nisso porque, no momento que dava erro, eu ainda tinha bastante espaço livre (bastante, entenda-se  cerca de 10gb).

Obrigado pela força!

**Comment by wandersonsousa** [comment]
Instalei o postgres localmente e resolveu
