### ISSUE TITLE
Retornar 204 se informações para um determinado CNPJ não forem encontradas.

### ISSUE THREAD

**Issue by IsaqueMansur** [cuducos/minha-receita#187]
[Sugestão de melhoria]
Bom dia.
Por padrão, quando um "body" ou "param" é enviado de maneira coerente e não são localizados dados para retornar, o status da requisição retornado é o 204 (no content).
Isso ajuda bastante o desenvolvimento dos consumidores da API, evitando soluções pouco sustentáveis como essa:
`if (data.message && data.message.includes('inválido'))...`

**Comment by cuducos** [comment]
> Por padrão, quando um "body" ou "param" é enviado de maneira coerente e não são localizados dados para retornar, o status da requisição retornado é o 204 (no content).

Não é esse o meu entendimento dos status de resposta HTTP. 204 significa _sem conteúdo_, e não conteúdo inexistente. Quando um CNPJ _não é encontrado_ me parece mais sensato retornar 404 que significa exatamente (e literalmente) _não encontrado_.

Inclusive, retornar 204 (sem conteúdo) pode levar à interpretação equivocada de que o CNPJ existe mas que o servidor não tem ou não pode retornar o conteúdo dele (o que não é o caso).
