### ISSUE TITLE
Atualização dos dados

### ISSUE THREAD

**Issue by tirlone** [cuducos/minha-receita#188]
Olá pessoal, como vai??

Gostaria de saber se houve algum problema com a atualização dos dados da receita, visto que a última atualização aconteceu (segundo o json) em 12/04/2023.

Muito obrigado

**Comment by cuducos** [comment]
Houve um problema grave. Esqueci! Hahaha… vou começar uma atualização hoje. Obrigado pelo lembrete : )

**Comment by tirlone** [comment]
Obrigado Eduardo!!!

Aliás, se você puder por gentileza, poderia mandar a chave pix para eu
fazer a doação? Não tenho como mandar via carteira/bitcoin neste momento.

Abraço,

Lucas

Em seg., 10 de jul. de 2023 17:02, Eduardo Cuducos ***@***.***>
escreveu:

**Comment by cuducos** [comment]
Obrigado 💜  Veja se esse QR code funciona:

![Pix](https://github.com/cuducos/minha-receita/assets/4732915/662e4a00-1164-4626-824a-73630a64a6b6)

**Comment by cuducos** [comment]
Só passando para avisar: verifiquei hoje cedo e agora está atualizado : )

```curl
$ curl https://minhareceita.org/updated
{"message":"2023-06-30 é a data de extração dos dados pela Receita Federal."}
```

**Comment by tirlone** [comment]
Valeu!!!!

E eu fiz o pix agora há pouco.

Parabéns pelo trabalho!

Em ter., 11 de jul. de 2023 09:18, Eduardo Cuducos ***@***.***>
escreveu:

**Comment by tirlone** [comment]
Eduardo,

Se você quiser, eu posso me oferecer para atualizar os dados ou ajudá-lo a
pensar em uma forma de automatizar a atualização.
Algum robô que verifique diariamente em algum lugar se eles foram
atualizados e depois faça a atualização com os novos arquivos.
Não sei se algo assim seja possível, mas fica a sugestão.

Abs,

Lucas

Em ter., 11 de jul. de 2023 09:18, Eduardo Cuducos ***@***.***>
escreveu:
