### ISSUE TITLE
Downloading error: x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by fmercurio** [cuducos/minha-receita#19]
Using docker-compose.
After run command bellow:
`$ docker-compose run --rm minha-receita download --directory /mnt/data/`

The following error is presented:

```
2020/12/18 21:51:47 Preparing to downlaod from the Federal Revenue official website…
Downloading   0% |                                                                                                           | (60 kB/6.7 GB, 173.613 kB/s) [0s:11h10m17s] panic: Get "https://cnae.ibge.gov.br/images/concla/documentacao/CNAE_Subclasses_2_3_Estrutura_Detalhada.xlsx": x509: certificate signed by unknown authority
```

**Comment by arthurfrancioni** [comment]
Hello, I solved adding certificate in Dockerfile

`
FROM golang:1.15.3-buster as build
WORKDIR /minha-receita
ADD go.* ./
ADD main.go .
ADD api/ ./api/
ADD cmd/ ./cmd/
ADD db/ ./db/
ADD download/ ./download/
ADD testdata/ ./testdata/
ADD transform/ ./transform/
RUN go get && go test ./... && go build -o /usr/bin/minha-receita

FROM debian:buster-slim
RUN apt-get update && \
    apt-get install -y postgresql-client && \
    apt-get autoremove -y && \
	apt-get install -y --no-install-recommends ca-certificates && \
    rm -rf /var/lib/apt/lists/*
	
RUN update-ca-certificates

COPY --from=build /usr/bin/minha-receita /usr/bin/minha-receita
ENTRYPOINT ["/usr/bin/minha-receita"]
CMD ["api"]
`

**Comment by cuducos** [comment]
Muito obrigado, @arthurfrancioni! Eu ia explorar esse erro hoje, mas voce já resolveu : )

Eu apenas instalaria os certificados na mesma linha do cliente PostgreSQL e executaria a atualização dos certificados no mesmo `RUN` para ter uma imagem mais enxuta e fácil de manter. Se quiser abrir um PR, é mais do que bem-vindo 💜
