### ISSUE TITLE
CNPJ faltando em base local (não no servidor do projeto)

### ISSUE THREAD

**Issue by cleltonhenrique** [cuducos/minha-receita#192]
Boa tarde Eduardo!
Gostei muito do minha receita, e estou montando um dataSet com os dados da receita, 
porém estou tendo alguns problemas que acredito que você também teve com:
Dados duplicados e faltam alguns dados na base, 
por exemplo consulto um um cnpj 07224991001530 na minha base, PostgreSQL,
depois de subir os  N arquivos de dados e não encontro a informação este cnpj não é encontrado
porem no minha receita ele é encontrado, alem da base "disponibilizada" pela Receita, você consultou 
alguma outra fonte, poderia me dar alguma dica? 
Muito obrigado, um abraço.

**Comment by cuducos** [comment]
Oi, @cleltonhenrique : )

> Gostei muito do minha receita, e estou montando um dataSet com os dados da receita

Uhuu 💜 

> porém estou tendo alguns problemas que acredito que você também teve com:
> Dados duplicados

Sim, tive mesmo — registrado no #149 bem como nas _issues_ e PRs linkados lá ; )

> e faltam alguns dados na base,
> por exemplo consulto um um cnpj 07224991001530

Pois é, esse CNPJ [existe](https://https://minhareceita.org/07224991001530) nos dados abertos — qual a versão (data de extração) dos dados que você está utilizando? Tem certeza que baixou todos os arquivos `ESTABELE*.zip`?

> você consultou alguma outra fonte, poderia me dar alguma dica?

Sim, [como documentado](https://docs.minhareceita.org/servidor/#download-dos-dados). Mas isso não faria ter mais um CNPJ. Isso é apenas para pegar o código dos municípios pelo IBGE.

Me parece mais um caso de ou arquivo faltando, ou de erro no processo de subir os dados.

**Comment by cuducos** [comment]
Troquei o título pois o outro insinuava falta de transparência do projeto — o que não é o caso. Como registrei no comentário anterior, não há nada _escondido_.

**Comment by cuducos** [comment]
Fechando por inatividade. Fiquem de boa para re-abrir com novidades : )

**Comment by ginatto** [comment]
Incrivelmente estou com um problema semelhante mas como estou ainda no início e estruturando e usando no Power BI não posso afirmar, mas sei que alguns cnpjs não consigo acessar localmente.

**Comment by cuducos** [comment]
O que você quer dizer com “alguns cnpjs não consigo acessar localmente” — via web API local?

**Comment by ginatto** [comment]
eu vou baixar novamente os arquivos, e depois eu vou verificar! ai te dou um feedback. grato.
