### ISSUE TITLE
Email da empresa vindo NULL

### ISSUE THREAD

**Issue by leonardolb** [cuducos/minha-receita#196]
Bom dia! Reparei que o campo e-mail está vindo nulo.

Eu li os outros comentários sobre a privacidade do e-mail, porém esse é o e-mail de contato da Empresa em si, disponível no cartão CNPJ. Não seria interessante retorná-lo? 

Por exmeplo, é o e-mail oficial de contato para notificações importantes e etc.

**Comment by cuducos** [comment]
> Bom dia! Reparei que o campo e-mail está vindo nulo.

Que bom, MInha Receita funcionando [como esperado](https://docs.minhareceita.org/servidor/#questoes-de-privacidade).

> Não seria interessante retorná-lo?

Não, _o e-mail oficial de contato para notificações importantes e etc._ também pode ser utilizado para _spam_ e mensagens não solicitadas.

 Mas você pode criar seu próprio servidor com os emails se quiser, sem problemas — o link acima documenta o _como_ ; )

**Comment by leonardolb** [comment]
Sim, por sinal, parabén!
