### ISSUE TITLE
requisições por segundo

### ISSUE THREAD

**Issue by ThaJustino** [cuducos/minha-receita#198]
Olá pessoal,

Alguém poderia me dizer quantas requisições por segundo essa API permite?
Caso essa informação esteja em algum lugar, poderiam me instruir onde localizar?

Desde já, agradeço!

**Comment by cuducos** [comment]
[Da documentação](https://docs.minhareceita.org/#limites-do-prototipo):

> O protótipo não tem nenhuma garantia de nível de serviço

Ou seja: não tem limite pre-estabelecido. Use. Se cair, caiu. Se respoder, respondeu.

**Comment by cuducos** [comment]
Para referência com dados dos últimos 30 dias:

![image](https://github.com/cuducos/minha-receita/assets/4732915/d91ecdde-a2b5-4d0c-abdf-92b250014442)

Nos momentos de pico foram quase 3k requisições/min. Ou seja, cerca de 50 requisições/s. E o tempo de resposta era inferior a 4ms. Ou seja, tava longe de _não aguentar_ ainda…
