### ISSUE TITLE
Dúvida/Possível bug no updated

### ISSUE THREAD

**Issue by devmessias** [cuducos/minha-receita#199]
Olá pessoal! Muito obrigado por esse projeto. Estou com uma dúvida aqui. 

Ao realizar o curl na data de extração retorna `20/11/2023`

![image](https://github.com/cuducos/minha-receita/assets/6979335/3b62a70e-8612-4193-99ae-c8cbe5c5e60c)

mas olhando no site vi que a última data de extração é 11/11/2023, tem uma data de atualização 20/11/2023 mas isso não seria data de atualização da página ou algo do tipo que não tem haver com os dados?
![image](https://github.com/cuducos/minha-receita/assets/6979335/fccdbee0-0005-4486-88ff-a968c50950ca)

fiquei pensando se o minhareceita não está extraindo esse dado por engano pq uma fonte comercial disponibiliza até dia 11/11/2023, e não consigo achar nenhum cnpj com data de inicio após 11/11/2023

![image](https://github.com/cuducos/minha-receita/assets/6979335/bbcb9563-c9d7-444a-b98c-a1199b4a72f7)

**Comment by cuducos** [comment]
Bem interessante essa diferença. Acho que faz sentido mudar sim. Até pq isso está iconsistente com a [documentação](https://docs.minhareceita.org/como-usar/#endpoints-auxiliares):

> JSON contendo a data de extração dos dados pela Receita Federal.

**Comment by devmessias** [comment]
É parece bug mesmo @cuducos . Criei um indice aqui no postgre e não parece ter nenhum CNPJ pos dia 11
![image](https://github.com/cuducos/minha-receita/assets/6979335/4d657fd5-784c-41c5-8181-117a6a637c13)

Chequei pelo CSV TB (estabelecimentos9.csv)

```
cut -d';' -f7 K3241.K03200Y9.D31111.ESTABELE > datas.csv
sort -n datas.csv | tail -n 20
```

output

```
"20231111"
"20231111"
"20231111"
"20231111"
"20231111"
"20231111"
"20231111"
"20231111"
"20231111"
"20231111"
"20231111"
"20231111"
"20231111"
"20231111"
"20231111"
"20231111"
"20231111"
"20231111"
 OFICINA DA CRIS"
S
```

**Comment by cuducos** [comment]
`OFICINA DA CRIS` 👀 

[Eu](https://twitter.com/cuducos/status/1646684441979281410) [adoro](https://twitter.com/cuducos/status/1479078346248097793) o cuidado que eles tem com data… hahaha…

**Comment by devmessias** [comment]
Essa data é obtida automaticamente né ? vou dar uma olhada no código
