### ISSUE TITLE
Teria como acessar o histórico de alteração dos CNAEs secundários?

### ISSUE THREAD

**Issue by takusuman** [cuducos/minha-receita#202]
Bom dia a todos os contribuidores desse projeto.

Haveria alguma forma de ter acesso ao histórico de mudança nos CNAEs ou essa API, por uma questão de simplicidade ou até mesmo de inviabilidade, não implementa esse acesso?
Acho inaceitável pagar 23 reais para ter acesso "oficial" a uma informação que poderia tranquilamente ser pública, então gostaria de saber se essa API já oferece isso.

**Comment by cuducos** [comment]
> gostaria de saber se essa API já oferece isso

Não, o que a API oferece é o que está documentado no [como usar](https://docs.minhareceita.org/como-usar/).

> Haveria alguma forma de ter acesso ao histórico de mudança nos CNAEs

Sim, no [FAQ](https://docs.minhareceita.org/faq) tem duas coisas que podem ser úteis:
* O espelho de dados com o que eu consegui coletar de dados das extrações mensais da Receita Federal.
* Aí você pode olhar as perguntas relacionadas a SQL e, ao subir cada “lote” de uma vez, analisar esses dados localmente para chegar a esse histórico.

**Comment by takusuman** [comment]
Desde já agradeço pela resposta, mas tenho mais uma pergunta:

> Aí você pode olhar as perguntas relacionadas a SQL e, ao subir cada “lote” de uma vez, analisar esses dados localmente para chegar a esse histórico.

Tem algum guia sobre como subir o SQL com o "lote" em específico? Eu dei uma batida de olho na documentação sobre subir o Docker, mas no caso eu só precisava do banco de dados "cru" mesmo para analisar entre Novembro de 2023 e Janeiro desse ano.

**Comment by cuducos** [comment]
> Tem algum guia sobre como subir o SQL com o "lote" em específico?

É o mesmo procedimento que você leu no Docker. Você baixa (manualmente) os arquivos do espelho de novembro, dezembro de 2023, janeiro de 2024. E carrega três bancos de dados diferentes com o `minha-receita transform`.

Eu carregaria Novembro, por exemplo, depois entraria no banco de mudaria o nome da tabela de `cnpj` para `cnpj_202311`. E aí carregaria dezembro. Repete o passo etc.

**Comment by takusuman** [comment]
> É o mesmo procedimento que você leu no Docker. Você baixa (manualmente) os arquivos do espelho de novembro, dezembro de 2023, janeiro de 2024.

Seriam aqueles .zip, certo? Todos?

> E carrega três bancos de dados diferentes com o `minha-receita transform`.
> 
> Eu carregaria Novembro, por exemplo, depois entraria no banco de mudaria o nome da tabela de `cnpj` para `cnpj_202311`. E aí carregaria dezembro. Repete o passo etc.

Certo, isso eu entendi.
Muitíssimo obrigado pela resposta rápida.

**Comment by cuducos** [comment]
> Seriam aqueles .zip, certo? Todos?

Todos das pastas que começam com 202311, 202312 e 202401 ; )

**Comment by takusuman** [comment]
> > Seriam aqueles .zip, certo? Todos?
> 
> Todos das pastas que começam com 202311, 202312 e 202401 ; )

E eu os junto no momento da extração ou os deixo em um diretório à parte para o ``minha-receita`` tomar alguma ação? Peço perdão pela pergunta pois ainda não li o código do programa.

**Comment by cuducos** [comment]
>  não li o código do programa

Não precisa ler o código do programa. O que você pergunta está na [documentação](https://docs.minhareceita.org/servidor/#tratamento-dos-dados):

> Para especificar onde ficam os arquivos originais da Receita Federal e do Tesouro Nacional, o comando aceita como argumento `--directory` (ou `-d`), sendo o padrão `data/`.

Ou seja, baixa cada “lote” em um diretório diferente, e use o `-d` para dizer qual lote importar.

**Comment by takusuman** [comment]
Excelente.
Obrigado mesmo e uma boa noite.
