### ISSUE TITLE
API fora do ar

### ISSUE THREAD

**Issue by Leocamarggo** [cuducos/minha-receita#204]
Bom dia, pessoal! Primeiramente, parabéns pelo projeto.

Estive utilizando a API nos ultimos dias e notei que a mesma esta fora do ar.
Está retornando `Error code 522` no Cloudflare. 

![image](https://github.com/cuducos/minha-receita/assets/73756283/9c607857-9f0d-44aa-ab00-2141292af0cb)

Gostei bastante do projeto e queria saber se pretendem colocar no ar novamente.

Desde já, obrigado :)

**Comment by cuducos** [comment]
O servidor caiu. Estou olhando o que foi e vendo o que fazer para voltar pro ar. Obrigada por avisar : )

**Comment by cuducos** [comment]
O data center que a Minha Receita utiliza está realizando uma manutenção em caráter de urgência: https://contabo-status.com/

**Comment by cuducos** [comment]
Não há nada que a gente possa fazer, nem por SSH o servidor está acessível. O tempo esperado para manutenção é de 45min. Vou acompanhar.

**Comment by Lucas-Angelo** [comment]
> O data center que a Minha Receita utiliza está realizando uma manutenção em caráter de urgência: https://contabo-status.com/

Essa manutenção começou dia 12/02?

**Comment by eitchtee** [comment]
@cuducos é impressão minha ou a manutenção estava prevista pra começar dia 12 e tá rodando até hoje?

Emendaram o carnaval no datacenter

**Comment by Lucas-Angelo** [comment]
Dureza, no dia de apresentação do projeto KK

**Comment by cuducos** [comment]
> Dureza, no dia de apresentação do projeto

Quem bom que é código (e dados) aberto. Assim você pode subir localmente, ou num servidor teu parta fazer a apresentação ; )

**Comment by cuducos** [comment]
@Lucas-Angelo e @eitchtee: Sim, o cronograma parece furado. Estou aguardando contato do suporte deles.

**Comment by cuducos** [comment]
Ok, o servidor voltou ao ar, mas aparentemente perdeam o banco de dados. Vou iniciar um novo processo do ETL, mas isso leva cerca de 2h. 

Ainda estão em manutenção e talvez isso se perca novamente. Vou monitorar.

**Comment by eitchtee** [comment]
> mas aparentemente perdeam o banco de dados

Rapaz, que viagem

@cuducos já pensou em transferir pro [Oracle Cloud Free Tier](https://www.oracle.com/cloud/free/)? São 24gb de RAM e, se não me engano, 240gb de armazenamento de graça. A única pegadinha é que a CPU é ARM, então sua imagem do Docker, se você usar ela internamente, tem que suportar essa arquitetura.

Acho que seria uma boa pra reduzir seu custo mensal a 0, uso o serviço deles tem quase um ano e até hoje sem problemas (ou cobranças)

**Comment by cuducos** [comment]
> Rapaz, que viagem

Para facilitar a vida, uso [Dokku](https://dokku.com/). Como resultado, o banco de dados persiste dados em um volume do Docker. Provavlemente isso não é o padrão e se perdeu.  

> 240gb de armazenamento de graça

Isso não suporta _dois_ banco de dados do Minha Receita em paralelo.
E uma vez por mês preciso disso para fazer a migração sem tirar o servidor do ar.
Então o custo mensal seria bem maior do que os 13USD que pago hoje.

**Comment by cuducos** [comment]
Apenas atualizando com o progresso do ETL carregando os dados, já foi mais da metade:

```
2024/02/15 15:34:12 Dropping table public.cnpj…
2024/02/15 15:34:12 Creating table public.cnpj…
2024/02/15 15:34:13 Saving the updated at date to the database…
2024/02/15 15:34:13 Loading Simples files…
2024/02/15 15:34:13 Loading Empresas files…
2024/02/15 15:34:13 Loading Socios files…
Processing base CNPJ, partners and taxes 100% |███████████████████████| (117544995/117544995, 26390 it/s)              
2024/02/15 16:50:24 Loading Estabelecimentos files…                                                                    
Creating the JSON data for each CNPJ  43% |███████████               | (25755648/59128283, 12311 it/s) [1h5m52s:45m10s]
```

**Comment by Lucas-Angelo** [comment]
> Reestabelecida. Ufa! Obrigada a todo mundo que reportou, deu força, apoiou e deu sugestões de melhoria! Espero que a apresentação dê certo/tenha dado certo, @Lucas-Angelo : )

Deixarmos para preencher manual, mas deu bom eu acho kkk

**Comment by evandrosl-hisofi** [comment]
Creio que o problema voltou
![image](https://github.com/cuducos/minha-receita/assets/129754540/1a6f334d-acd6-40ea-8bd6-d44bcb136e9f)

**Comment by b2evandro** [comment]
Acho que está ocorrendo novamente 
![image](https://github.com/cuducos/minha-receita/assets/55710708/a1011849-160f-44cd-ae81-687e5ae88a37)

**Comment by cuducos** [comment]
Assim [como da outra vez](https://github.com/cuducos/minha-receita/issues/204#issuecomment-1946213999) o servidor voltou, mas o banco de dados não. Iniciei o processo de subir os dados novamente — leva algumas horas.

**Comment by cuducos** [comment]
Se alguém tiver alguma sugestão de outro servidor, estou aberto. Descrevi [aqui](https://tech.lgbt/@cuducos/112122411562358026) e [aqui](https://bsky.app/profile/cuducos.me/post/3ko2fe72jx42j) o básico dos requisitos e valores:

> I am looking for a new server for Minha Receita — https://github.com/cuducos/minha-receita
> 
> I currently use Contabo, but two outages in roughly a month are too much.
> 
> I pay 13 USD/month for a VPS. The crucial is 400Gb storage. Currently, I have 6 vCPU, 16Gb RAN and 32Tb traffic.
> 
> Any recommendation?

**Comment by Cauen** [comment]
Opa @cuducos 
Quanto você usa dessa configuração toda?

Esse ano, depois do resultado da pesquisa da [Stackoverflow](https://survey.stackoverflow.co/2023/#section-admired-and-desired-cloud-platforms) migrei da Digitalocean pra a top 1 da pesquisa: [Hetzner - link de convite](https://hetzner.cloud/?ref=jZQq6bZRKHEl)

Tem me atendido muito bem, mas esse preço aí eles não batem, mas acredito que ficaria algo em torno de 50 euros mensais (16 ram, 4vCPU, extra volume, + extra traffic), se você precisar de tudo isso.

**Comment by cuducos** [comment]
> Quanto você usa dessa configuração toda?

Como eu disse:

> The crucial is 400Gb storage

Pq? Como documentado [aqui](https://docs.minhareceita.org/instalacao/#requisitos), um bancod e dados ocupa ~150Gb. Como (para evitar downtime) preciso eventualmenet de _dois_ banco de dados (o do mês anterior, e o do mês que estou importando), o armazenamento precisa ser um pouco além de 300Gb.

Vou olhar o Hetzner com calma no final de semana — obrigada por compartlhar, @Cauen. Deve ficar um pouco mais caro, mas dá para aguentar…

**Comment by Cauen** [comment]
Então vai ficar uns € 35 e.e

![image](https://github.com/cuducos/minha-receita/assets/8796757/5a1585ec-25bb-439d-8c60-703dc235a4ce)
![image](https://github.com/cuducos/minha-receita/assets/8796757/74dd0088-eb66-4b4e-8519-27d936664e77)

**Comment by cuducos** [comment]
Provavelmente em mais 1h deve estar reestabelecida:

```console
$ minha-receita transform -b 32768 -m 16
2024/03/19 13:35:56 Saving the updated at date to the database…
2024/03/19 13:35:56 Loading Simples files…
2024/03/19 13:35:56 Loading Empresas files…
2024/03/19 13:35:56 Loading Socios files…
Processing base CNPJ, partners and taxes 100% |███████████████████| (118378801/118378801, 24887 it/s)              
2024/03/19 14:55:36 Loading Estabelecimentos files…                                                                
Creating the JSON data for each CNPJ  14% |███                     | (8454144/59495419, 20501 it/s) [16m56s:41m29s]
```

**Comment by yvescleuder** [comment]
Parece que ainda está com problema
https://brasilapi.com.br/api/cnpj/v1/37933858000119

![image](https://github.com/cuducos/minha-receita/assets/15827896/de19010b-ba5c-44ce-aa05-576ae7933805)

**Comment by cuducos** [comment]
> Parece que ainda está com problema

Se a _issue_ está aberta, é pq ela não foi resolvida ainda ; )

**Comment by brunopapait** [comment]
Ainda fora do ar quando vou buscar algum CNPJ .. Algum parecer ?

**Comment by cuducos** [comment]
> Ainda fora do ar quando vou buscar algum CNPJ

Sim, justamente por isso [a issue está aberta ainda](https://github.com/cuducos/minha-receita/issues/204#issuecomment-2007975344).

> Algum parecer ?

[Sim](https://github.com/cuducos/minha-receita/issues/204#issuecomment-2007297151). Quando terminar ou tiver uma mudança eu comunico aqui.

**Comment by cuducos** [comment]
O servidor está bastante instável. O servidor de DNS não consegue conexão, o banco de dados perde conexão também. Estou reiniciando o processo de subir os dados, mas não vou conseguir monitorar mais hoje.

**Comment by cuducos** [comment]
Aparentemente restaurada! Obrigada todo mundo que reportou/deu ideais/acompanhou/ajudou 💜

**Comment by duartepkarol** [comment]
Bom dia! Aparentemente a API caiu novamente. 
![image](https://github.com/cuducos/minha-receita/assets/153635270/3626729a-6e62-43d6-878e-ad7601848b06)

A minha receita tbm está fora 🥲
![image](https://github.com/cuducos/minha-receita/assets/153635270/38300df4-3cb8-4358-a478-cb2162292e4d)

Caiu novamente mesmo?

**Comment by cuducos** [comment]
> Caiu novamente mesmo?

Sim. Mais uma vez inacessível nem por SSH 💔

**Comment by cuducos** [comment]
Até ter esse acesso, não há nada que possa afzer (migrar de servidor não consigo hoje; apenas no final de semana).

**Comment by cuducos** [comment]
Aparentemente, retornou ao normal.

**Comment by cuducos** [comment]
E o banco de dados se perdeu outra vez.

**Comment by carlosmixz** [comment]
Pelo jeito está normal agora!

**Comment by cuducos** [comment]
@carlosmixz não está.

Ainda não completou o carregamento de cerca de 8% dos CNPJs, e o banco de dados está sem índices (resposta mais demoradas):

```
2024/03/20 19:37:55 Loading Estabelecimentos files…
Creating the JSON data for each CNPJ  92% |████████████████████████████████████████████████████████████      | (55001088/59495419, 11622 it/s) [1h13m30s:6m26s]

```

**Comment by Leticiamacedo10** [comment]
Olá! Boa tarde! Ainda não consigo utilizar o API.

**Comment by cuducos** [comment]
> Olá! Boa tarde! Ainda não consigo utilizar o API.

Como esperado, dado que essa _issue_ ainda está aberta ; )

**Comment by cuducos** [comment]
Ok. Falei com o suporte — eles só responderam agora, depois de dois dias. Disseram que tiveram manutenção, mas que deve estar tudo 100% agora. Subi novamente o banco de dados. Veremos se agora fica — pelo menos até o final de semana quando, se eu tiver tempo, vou tentar mudar de servidor.

**Comment by cuducos** [comment]
No momento o servidor não me dá nem acesso SSH, então não há o que fazer. Vou atualizando aqui.

**Comment by cuducos** [comment]
Existem algumas manutenções planejadas para hoje em https://contabo-status.com/ — aguardemos.

**Comment by cuducos** [comment]
@Jpmmdf — sem custos é a tua ajuda, ou OCI? Pois os preços de rodar o Minha Receita no OCI passam *muito* os 20 USD/mês que [o projeto arrecada](https://github.com/sponsors/cuducos). Os serviços _always free_ não aguentam [os requisitos](https://github.com/cuducos/minha-receita/issues/204#issuecomment-2007082126).

A propósito, o servidor continua sem acesso SSH, vai ficar para amanhã a resolução.

**Comment by mat-aranha** [comment]
Fala, pessoal!

O servidor voltou a responder, mas aparentemente o banco foi perdido novamente 
![IMG_3290](https://github.com/cuducos/minha-receita/assets/89228905/e6e72a7a-0f6c-43e2-94f3-2abc172161c9)

**Comment by cuducos** [comment]
POr alguma bizarrice, isso já aconteceu [outras](https://github.com/cuducos/minha-receita/issues/204#issuecomment-2007048730) [vezes](https://github.com/cuducos/minha-receita/issues/204#issuecomment-1946213999).

Vou terminar de baixar os dados de abril a subir o banco novo. Aviso aqui quando terminar — e fecho a _issue_ outra vez. Ufa.

**Comment by mat-aranha** [comment]
Boa!

**Comment by hslira** [comment]
A chamada na API agora retorna o espelho de dados do projeto, não o resultado da chamada.
Isso faz com que o monitor indique que a API está operacional, mas qual utilizada, retorna um erro.

**Comment by hslira** [comment]
@cuducos , eu acho ótimo o projeto e sempre gosto de ajudar propostas Open Source que ajudam desenvolvedores de companhias pequenas ou independentes.
Caso tenha alguma sugestão de meta de valor para migrar o serviço para algum provedor que julgue mais adequado, fique a vontade para falar comigo!
Abs e parabéns pelo projeto e dedicação

**Comment by SelmoMariano** [comment]
Caro Edu, boa tarde!

Amigo, 
Tem previsão de quando a API voltará a funcionar?
Gratidão sempre.
Abraço,

**Comment by gilbertogara** [comment]
Boa tarde pessoal, tranquilo? Acredito que o retorno da API ainda esteja errado, só reforçando o que o [hslira] disse acima ali.

**Comment by cuducos** [comment]
Gente, eu sei. Eu momento algum assumi que o problema estava resolvido. Se eu não falei que estava resolvido, e mantive a issue aberta, por favor, não gerem mais ruído.

**Comment by cuducos** [comment]
> Tem previsão de quando a API voltará a funcionar?

Não.

**Comment by cuducos** [comment]
> Caso tenha alguma sugestão de meta de valor para migrar o serviço para algum provedor que julgue mais adequado, fique a vontade para falar comigo!

A [meta](https://github.com/sponsors/cuducos) sempre foi pública.

**Comment by cuducos** [comment]
API reestabelecida.
