### ISSUE TITLE
Relacionar Tabelas csv do mirror para usar no Power BI localmente

### ISSUE THREAD

**Issue by ginatto** [cuducos/minha-receita#208]
Primeiramente gostaria de agradecer ao projeto fantástico. Estou com algumas ideias entre elas pesquisar clientes, portanto inicialmente achei interessante usar o Power BI para visualizar os dados filtrados. Apesar de entender de tecnologia, estou aprendendo JSON e BI e estou usando isso como estudo de caso dito isso.

Depois de baixar todos os arquivos encontrados em mirror.minhareceita.org peguei a data mais recrescente 2024.02.22 então eu peguei os principais arquivos CSV para extrair as informações dos seguinte arquivos 
K3241.K03200Y0.D40210.EMPRE.CSV e K3241.K03200Y0.D40210.ESTABELE.CSV como eu faço a relação entre elas?

![Imagem do WhatsApp de 2024-03-15 à(s) 12 33 42_04c0dbd9](https://github.com/cuducos/minha-receita/assets/160131591/8eaace0f-8afa-42ea-938c-ba37d7075c30)

**Comment by cuducos** [comment]
> como eu faço a relação entre elas?

Isso é explicado no que a Receita Federal chama de _Dicionário de Dados do Cadastro Nacional da Pessoa Jurídica_ e está na [página oficial dos dados](https://dados.gov.br/dados/conjuntos-dados/cadastro-nacional-da-pessoa-juridica---cnpj). Como o Minha Receita processa é explicado no [guia de contribuição](https://github.com/cuducos/minha-receita/blob/main/CONTRIBUTING.md#arquitetura-n%C3%BAmero-do-cnpj-e-estrutura-do-pacote-transform).
