### ISSUE TITLE
Como configurar uma VPS própria?

### ISSUE THREAD

**Issue by carlosmixz** [cuducos/minha-receita#210]
Olá, estou precisando configurar a API em uma VPS própria, entretanto não consegui seguindo o que está em https://docs.minhareceita.org/. Seria possivel explicar melhor em outro lugar (ou atualizar as documentações) ou cobrar para configurar para mim?

**Comment by cuducos** [comment]
@carlosmixz, _explicar melhor_ é muito vago. Você me ajudaria a te ajduar dando mais detalhes do que vocie tentou, do porquê não conseguiu, se treve erro, qual erro, logs etc.

A documentação está atualizada. É o que eu uso atualmente. Claro que pode ser melhorada, mas com um comentário vago como “entretanto não consegui seguindo” fica difícil saber onde melhorar.

**Comment by cuducos** [comment]
Fechando por inatividade. Quando tiver mais detalhes, aí reabrimos : )

**Comment by cawecoy** [comment]
Só queria deixar um registro que talvez ajude outras pessoas como eu que teve dúvidas... a API funciona acessando o IP do seu servidor com `:8000` no final. Suponha que o IP do seu servidor é `192.111.111.11` e você queira pequisar o CNPJ `33.683.111/0002-80`. Então o URL ficará assim: [http://192.111.111.11:8000/33.683.111/0002-80](http://192.111.111.11:8000/33.683.111/0002-80)
