### ISSUE TITLE
CNPJ válidos retornando como inválidos

### ISSUE THREAD

**Issue by SelmoMariano** [cuducos/minha-receita#211]
Olá pessoal, 
Tudo bem?
Gostaria de parabenizar os abnegados em sempre estarem contribuindo com excelentes soluções.
Nos últimos dias percebi um instabilidade no serviço de consulta.
Quando foi hoje, percebi que o serviço voltou, porém quando vou consultar CNPJs que são válidos está retornando como CNPJ Inválido.
Sabem informar se está ocorrendo algum problema?

Gratidão

**Comment by cuducos** [comment]
@SelmoMariano, agora que a API (aparentemente) retornou ao normal, isso ainda continua acontecendo? Se sim, me dê algum(ns) exemplo(s) de número de CNPJ que você está utilizando.

**Comment by SelmoMariano** [comment]
> @SelmoMariano, agora que a API (aparentemente) retornou ao normal, isso ainda continua acontecendo? Se sim, me dê algum(ns) exemplo(s) de número de CNPJ que você está utilizando.

**Comment by SelmoMariano** [comment]
> > @SelmoMariano, agora que a API (aparentemente) retornou ao normal, isso ainda continua acontecendo? Se sim, me dê algum(ns) exemplo(s) de número de CNPJ que você está utilizando.

Olá, infelizmente o problema ainda continua.

Já consultei alguns CNPJs que conhenço e API retorna que o CNPJ não encontrado.

EX: 
05.285.268/0001-30
12.347.102/0001-67

**Comment by SelmoMariano** [comment]
Olá, infelizmente o problema ainda continua.

Já consultei alguns CNPJs que conhenço e API retorna que o CNPJ não encontrado.

EX:
05.285.268/0001-30
12.347.102/0001-67

**Comment by cuducos** [comment]
Então é o mesmo problema da #204. Perda do banco de dados no servidor.
