### ISSUE TITLE
Erro 404 ao realizar busca de CNPJ

### ISSUE THREAD

**Issue by lucasvini382** [cuducos/minha-receita#212]
Olá estou tomando erro ao realizar a busca de um CNPJ. Segue requisição que está sendo realizada.
`curl --location 'https://minhareceita.org/27484015000129'`
![Captura de tela 2024-03-20 150310](https://github.com/cuducos/minha-receita/assets/77305388/037ba3a8-a91a-4017-87c1-326afee6d568)

**Comment by cuducos** [comment]
Ver #204
