### ISSUE TITLE
Agradecimento

### ISSUE THREAD

**Issue by SelmoMariano** [cuducos/minha-receita#213]
Prezado,

Quero agradecer pelo seu empenho em resolver no dia de ontem os problemas vinculados à consulta do CNPJ.

Seu trabalho e dedicação tem extrema relevância para muitos profissionais.

Estou em uma fase de lançamento de uma Startup, e nesse momento não tenho caixa, e não monetizei nenhum centavo, no entanto, assim que possível, terei enorme satisfação em poder contribuir com a continuidade do seu importante trabalho.

Gratidão,

**Comment by cuducos** [comment]
Muito obriagda 💜 
Esse projeto é minha paixão… pena eu não ter mais tempo e dinheiro para fazer ele melhor ainda!

**Comment by SelmoMariano** [comment]
Olá Eduardo, tudo bem?

Pelo visto a API está funcionando de forma estável, mas gostaria de saber se conseguiu fazer a mudança de servidor como havia comentado.

Que você tenha uma semana de muitas bençãos.

Abração

**Comment by cuducos** [comment]
> gostaria de saber se conseguiu fazer a mudança de servidor como havia comentado.

Infelizmente não tive tempo.
