### ISSUE TITLE
Erro - self-hosted - docker-compose run --rm minha-receita transform -d /mnt/data/

### ISSUE THREAD

**Issue by mbkcontabilidade** [cuducos/minha-receita#214]
Boa noite! Tenho uma empresa de contabilidade e estamos fazendo um self-hosted do minha-receita para uso interno. Sou um contador corajoso mas sem muita experiencia como sysadmin, então fico meio preso em algumas coisas como essa:

Tenho uma instancia de proxmox e criei um container rodando ubuntu e comecei a instalação usando docker compose. 

Postgres online e saudavel conforme portainer apontou.

Deu certo ate a parte do download, onde precisei colocar um timeout e retry bem alto usando o mirror de 22/02/2024 pra finalizar, mas eventualmente finalizou. 

O "check" nao retornou nada. Retornou ao terminal sem mensagem de "ok" ou algo do genero.

Ao rodar docker-compose run --rm minha-receita transform -d /mnt/data/, ele rodou ate 63% e ali ficou. 

Eu dei 8GB de RAM e 500GB storage com 2 nucleos para a LXC. Seria falta de ram a razao que ele travou em 63% e nao se moveu por horas? No sumario foi possivel ver que estava usando os 8GB, e o processador varia de 40 a 60% de uso, mas a porcentagem nao mudou pelas ultimas 6 horas. 

Minha pergunta: Se eu configurar o 'transform' para nao usar o default de 8 simultaneos e usar apenas 2 ou 4, ele vai, eventualmente, usar a mesma quantidade de RAM e travar no meio do processo? Nessa instancia (Dell T140) tenho apenas 16GB de ram.

Agradeço qualquer insight.

**Comment by mbkcontabilidade** [comment]
Tentando agora novamente com

docker compose run --rm minha-receita transform --database-uri postgres://minhareceita:minhareceita@[ipdolxc]:5432/minhareceita?sslmode=disable --directory /mnt/data --max-parallel-db-queries 2 --no-privacy

**Comment by cuducos** [comment]
Ver #176

**Comment by mbkcontabilidade** [comment]
Valeu! Vou estudar as possiveis solucoes caso trave novamente. Dei 12GB e 3 nucleos dessa vez e ja esta em 70%, sem travamentos. Acho que agora vai.

**Comment by mbkcontabilidade** [comment]
Correção: Socio Files tava em 100%... tem mais uma porrada de arquivos rs ok agora as 20 horas fazem sentido
