### ISSUE TITLE
Erro ao fazer o download

### ISSUE THREAD

**Issue by naanzitos** [cuducos/minha-receita#221]
Olá, primeiramente parabéns pelo projeto! 

Já usei várias vezes para baixar a base, fazer o transform e etc...  Mas dessa vez está dando esse erro:
`
error downloading files from the federal revenue: could not create a progress file: error loading existing progress file: download progress file /root/.chunk/8287b6eeed63dcbd4eb985501de768c7-Estabelecimentos7.zip has unexpected number of chunks 323, expected 321
`

comando utilizado: 

`minha-receita download -d data`

Ao tentar utilizar um mirror, também está dando erro:

`error getting mirror urls: error decoding response body: invalid character '<' looking for beginning of value`

comando utilizado: 

`minha-receita download -d data/ -m 2024-03-20`

Pode me ajudar? 

Desde já, obrigado

**Comment by cuducos** [comment]
Minha desconfiança é que `error loading existing progress file` quer dizer que você tem um arquivo que marca o progresso (pedacinhos baixados e pedacinhos pendentes) que não bate com o tamanho do arquivo atual (por exemplo, a Receita federal trocou o arquivo online e agora ele tem tamanho diferente).

O ideal é reiniciar o download do começo. Com `minha-receita download --help` você pode opções como essa ; )

Teste o `minha-receita download --restart  -d data/ -m 2024-03-20` e me diga se vai? Aí pode fechar a _issue_ se resolver.

**Comment by naanzitos** [comment]
Era isso mesmo! Muito obrigado
