### ISSUE TITLE
Zeros a esquerda

### ISSUE THREAD

**Issue by hugonbgg** [cuducos/minha-receita#222]
Olá, primeiro parabéns pelo minha receita, estou usando localmente e funciona incrivelmente bem!
Tenho uma dúvida em relação aos zeros a esquerda, no postgres eles não aparecem na colunaid, já que a coluna tá como bigint, mas ao consultar a API o CPNJ é reconhecido quando consultado(desde que coloque o zero a esquerda). Minha dúvida é se o tratamento é feito na API mesmo ou não e também pq não usar text no lugar do bigint para os cnpjs(colunaid).
A dúvida/curiosidade surgiu quando pensei em filtrar os cpnjs só SP, notei isso e fiquei curioso para entender.
Um cpnj de exemplo: 00.000.400/0001-05

**Comment by cuducos** [comment]
> Minha dúvida é se o tratamento é feito na API mesmo ou não

No pacote `transform` [o número de CNPJ é transformado em inteiro](https://github.com/cuducos/minha-receita/blob/8415a00761c878fc93b7c1c2a65e7bd8d83cbafd/transform/venues.go#L24) antes de ser enviado para o banco de dados. No pacote `db` o CNPJ da URL (texto) também é [convertido para número inteiro](https://github.com/cuducos/minha-receita/blob/8415a00761c878fc93b7c1c2a65e7bd8d83cbafd/db/postgres.go#L127).

>  pq não usar text no lugar do bigint para os cnpjs

Performance e simplicidade: o campo não é dado, é apenas uma chave única. O CNPJ de verdade está na outra coluna.

> pensei em filtrar os cpnjs só SP

Isso explico como fazer em https://docs.minhareceita.org/faq
