### ISSUE TITLE
Dados não persistentes

### ISSUE THREAD

**Issue by hugonbgg** [cuducos/minha-receita#225]
Olá, fiz a instalação local recentemente e notei que os dados das tabelas sumiam depois de algum tempo, tanto no WSL como no Ubuntu direto, achei que era alguma configuração que fiz errado e comecei a explorar os logs do postgres. Notei que as tabelas são criada como UNLOGGED:
"2024-04-24 18:07:51.683 -03 [9221] minhareceita@minhareceita LOG:  comando: CREATE UNLOGGED TABLE IF NOT EXISTS public.cnpj (
	    id   bigint NOT NULL,
	    json jsonb NOT NULL
	);
	CREATE TABLE IF NOT EXISTS public.meta (
	    key   char(16) NOT NULL PRIMARY KEY,
	    value text NOT NULL
	)
"
Então quando o postgres não era encerrado corretamente elas eram corrompidas. Até simulei isso importando um data sample e matando o processo do postgres em seguida e aconteceu o mesmo problema, as tabelas continuam existindo, mas sem os dados.

Queria mais entender mesmo se foi uma escolha usar o unlogged mesmo. Pq acredito que vou criar como logged já que o ambiente que estou não é muito estável.

**Comment by cuducos** [comment]
> Queria mais entender mesmo se foi uma escolha usar o unlogged mesmo. 

As tabelas são criadas como `UNLOGGED` para acelerar a escrita dos dados. Acho que isso desvenda um bug de que quando o servidor cai #204, o banco de dados volta vazio!

Vou ver se dá para criar como `UNLOGGED` e depois de carregar os dados, mudar… sou meio nada em PostgreSQL!
