### ISSUE TITLE
Haverá atualização no banco de dados este mês?

### ISSUE THREAD

**Issue by carlosmixz** [cuducos/minha-receita#228]
Haviam atualizações no banco de dados em https://minhareceita.org/updated consistentemente todos os meses, mas mês passado não aconteceu. Houve alguma mudança nos planos pra esse servidor?

**Comment by carlosmixz** [comment]
![image](https://github.com/cuducos/minha-receita/assets/68700320/ed83752a-2609-449d-9ff1-81468459dd4c)

Aqui você pode ver o /updated indicando a data antiga.

![image](https://github.com/cuducos/minha-receita/assets/68700320/4d76cf84-38ff-48e7-916c-5a7cc533008b)

E aqui no espelho de dados, os ultimos são do dia 20/05/2024.

**Comment by cuducos** [comment]
Atualizado também — curiosamente vc escreveu enquanto o ETL rodava.
O download foi super lento esse mês.

**Comment by digitalisys** [comment]
Olá. Não houve atualização de dados da Receita no mês de junho/24?

**Comment by cuducos** [comment]
> Não houve atualização de dados da Receita no mês de junho/24?
Não. Mas ainda vai haver.
