### ISSUE TITLE
DownMonitor indicando Down desde 26 de abril.

### ISSUE THREAD

**Issue by carlosmixz** [cuducos/minha-receita#229]
O Down monitor neste link: https://stats.uptimerobot.com/tqpD6AQZqI está indicando que o sistema principal (minhareceita.org) está fora do ar desde o dia 26 de abril. Enquanto o mirror.minhareceita.org é indicado como funcional normalmente.

![image](https://github.com/cuducos/minha-receita/assets/68700320/8aff5beb-d5af-4ced-a5a3-ad831f9e529d)

**Comment by cuducos** [comment]
Muito obrigado, @carlosmixz — o endereço estava errado mesmo! Corrigido.
