### ISSUE TITLE
Erro ao rodar `transform` em docker.

### ISSUE THREAD

**Issue by mbkcontabilidade** [cuducos/minha-receita#244]
Hoje fui atualizar a base de dados postgres e o seguinte erro ocorreu:

root@minhareceita:~# docker run --rm -v /mnt/data:/mnt/data ghcr.io/cuducos/minha-receita:main transform -c -u postgres://minhareceita:minhareceita@192.168.0.105:5432/minhareceita?sslmode=disable -d /mnt/data -p -b 16384 -m 16
2024/10/02 17:26:09 Dropping table public.cnpj…
2024/10/02 17:26:09 Creating table public.cnpj…
2024/10/02 17:26:09 Loading Simples files…
2024/10/02 17:26:09 Loading Empresas files…
2024/10/02 17:26:09 Loading Socios files…
Processing base CNPJ, partners and taxes 100% || (124759553/124759553, 44097 it/s)                 
2024/10/02 18:13:31 Loading Estabelecimentos files…                                                
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xe8918a]

goroutine 101149912 [running]:
github.com/cuducos/minha-receita/transform.(*source).countLinesFor(0xc0217b4ba0, 0x0, 0xc02133bbc0, 0xc02133bc20)
        /minha-receita/transform/source.go:90 +0x6a
created by github.com/cuducos/minha-receita/transform.(*source).countLines in goroutine 1
        /minha-receita/transform/source.go:112 +0x97
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xe8918a]

goroutine 101149917 [running]:
github.com/cuducos/minha-receita/transform.(*source).countLinesFor(0xc0217b4ba0, 0x0, 0xc02133bbc0, 0xc02133bc20)
        /minha-receita/transform/source.go:90 +0x6a
created by github.com/cuducos/minha-receita/transform.(*source).countLines in goroutine 1
        /minha-receita/transform/source.go:112 +0x97
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xe8918a]

goroutine 101149915 [running]:
github.com/cuducos/minha-receita/transform.(*source).countLinesFor(0xc0217b4ba0, 0x0, 0xc02133bbc0, 0xc02133bc20)
        /minha-receita/transform/source.go:90 +0x6a
created by github.com/cuducos/minha-receita/transform.(*source).countLines in goroutine 1
        /minha-receita/transform/source.go:112 +0x97
        
Alguem ja se deparou com isso?

**Comment by mbkcontabilidade** [comment]
Ja li o issue #203 e #175, mas não encontrei solução.

**Comment by cuducos** [comment]
> /minha-receita/transform/source.go:90 +0x6a

O erro é ao ler o arquivo. Qual a saída de `minha-receita check`? Provavelmente o arquivo está corrimpido…

**Comment by pratadaniel94** [comment]
Resolvi o problema com `minha-receita check -x` para  remover os arquivos corrompidos, e `minha-receita download -x` para baixar os arquivos pendentes, e `minha-receita transform` para transformar novamente.
