### ISSUE TITLE
transform não avança além de "Loading Socios files"

### ISSUE THREAD

**Issue by cawecoy** [cuducos/minha-receita#248]
Primeiramente quero dizer que achei admirável o trabalho feito nesse repositório!

Instalação e download dos dados deram certo. Mas `transform` não avança além de `Loading Socios files`:

```sh
$ minha-receita transform
2024/10/08 12:37:50 Loading Simples files…
2024/10/08 12:37:50 Loading Empresas files…
2024/10/08 12:37:50 Loading Socios files…
```

Muito pouco CPU e RAM são utilizados pelo comando `transform`:

```sh
$ top

top - 13:21:02 up 20:20,  2 users,  load average: 0,25, 0,26, 0,32
Tasks: 440 total,   1 running, 439 sleeping,   0 stopped,   0 zombie
%Cpu(s):  0,3 us,  0,2 sy,  0,0 ni, 99,5 id,  0,0 wa,  0,0 hi,  0,0 si,  0,0 st
MiB Mem :  15768,3 total,    689,9 free,   6883,1 used,   8195,3 buff/cache
MiB Swap:      0,0 total,      0,0 free,      0,0 used.   7666,8 avail Mem 

    PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND                                                                                               
   4339 user      20   0 1156,4g 221652  91692 S   2,0   1,4  28:14.39 chrome                                                                                                
 217213 root      20   0 2789468  42252  20480 S   1,5   0,3   0:58.36 minha-receita
```

`transform -m 9 -p` e `transform --high-memory` dão na mesma. `check` não retornou nenhum problema.

Estou rodando em ambiente local com essas características:

```sh
# ~180GB de armazenamento disponível

$ df .
Filesystem     1K-blocks      Used Available Use% Mounted on
/dev/nvme0n1p6 402053392 192017008 189540000  51% /

# ~9GB de RAM disponível

$ free -m
               total        used        free      shared  buff/cache   available
Mem:           15768        5000        2879         729        7888        9701
Swap:              0           0           0

# CPU i7-11800H

$ cat /proc/cpuinfo  | grep 'name'| uniq
model name	: 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz

# Ubuntu 22.04.4

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.4 LTS
Release:	22.04
Codename:	jammy

# PostgreSQL 14.13

$ psql --version
psql (PostgreSQL) 14.13 (Ubuntu 14.13-0ubuntu0.22.04.1)

# Go 1.23.2

$ go version
go version go1.23.2 linux/amd64
```

Obs.: nunca programei em Go.

Será que falta configurar algo?

**Comment by cuducos** [comment]
Obrigada pelas palavras e pelo nível de detalhe : ) Eu fiquei com a impressão de que 9Gb de RAM poderia ser pouco, mas depois vi que o total é 15Gb. Não lembro de ter rodado o `transform` em uma máquina com menos de 16Gb hehehe…

Enfim, dois detalhes que vi que a gente pode explorar (e digo explorar pq não consegui ainda entender qual o gargalo ou bug aí):

* Vi ali que até tens memória disponível, mas zero de uso de swap. É uma opção configurar um swap para testar bem no espírito tentativa e erro?
* Vi que quando usasse o `df` o sistema de arquivos está montado em `/dev/nvme0n1p6`. Minha dúvida é se esse é o mesmo armazenamento do `/tmp` pois o `minha-receita` usa o `/tmp` para carregar sócios/empresas/dados do simples antes de ler o dataset principal (estabelecimentos). Se tem espaço em `/dev/nvme0n1p6` mas não em `/tmp` pode travar mesmo (e isso é uma baita oportunidade para o projeto: isso não é documentado de forma clara, nem é configurável (por exemplo, usar `$HOME/.cache` ou invés de `tmp`)

**Comment by cawecoy** [comment]
@cuducos disponha, eu quem agradeço pelo retorno!

> Vi ali que até tens memória disponível, mas zero de uso de swap. É uma opção configurar um swap para testar bem no espírito tentativa e erro?

Eu configurei um swap de 32GB, e não resolveu. Executei `transform` e verifiquei (mais de uma vez) que esse swap não está sendo usado:

```sh
$ free -m
               total        used        free      shared  buff/cache   available
Mem:           15768        9793         332        1073        5641        4564
Swap:          32767           2       32765

```

Sabe, parece que o comando está funcionando, mas muito lentamente, não sai disso aqui:

```sh
$ minha-receita transform
2024/10/08 12:37:50 Loading Simples files…
2024/10/08 12:37:50 Loading Empresas files…
2024/10/08 12:37:50 Loading Socios files…
```

Será que algo está limitando o uso de RAM e CPU do Go?

> Vi que quando usasse o `df` o sistema de arquivos está montado em `/dev/nvme0n1p6`. Minha dúvida é se esse é o mesmo armazenamento do `/tmp` (...)

Sim, verifiquei que `/tmp` corresponde ao armazenamento `/dev/nvme0n1p6`:

```sh
$ cd /tmp
$ df .
Filesystem     1K-blocks      Used Available Use% Mounted on
/dev/nvme0n1p6 402053392 192517448 189039560  51% /
```

Um detalhe é que tive que usar o `sudo go build` para compilar este aplicativo, sem o `sudo` não funcionava, assim como aconteceu com alguém https://github.com/cuducos/minha-receita/issues/118#issuecomment-1058480459

Estou achando que faltou configurar alguma coisa depois de instalar o Go...

**Comment by cuducos** [comment]
Ok, a instalção do Go é independente do `minha-receita`. Você pode nem instalar o Go e só baixar o binário que está tudo certo. Digo isso para diminuir o ruído. Na máquina de produção do minhareceita.org, por examplo, nem tem Go instalado! sobre o PostgreSQL, ele nem começou a ser utilizado nesse ponto ([você está no passo 2, PostgreSQL só entra no passo 4](https://github.com/cuducos/minha-receita/blob/main/CONTRIBUTING.md#estrat%C3%A9gia-de-carregamento-dos-dados-no-postgresql)).

Quando vc roda o `transform`, depois de um bom tempo (digamos, 20min) pode dar um `dh -hd1 /tmp` e um `ls -laGh /tmp`? (se não tiver nenhum dado sensível lá hehe)

**Comment by cawecoy** [comment]
@cuducos 

> Quando vc roda o transform, depois de um bom tempo (digamos, 20min) pode dar um dh -hd1 /tmp e um ls -laGh /tmp e no diretório dos dados? (se não tiver nenhum dado sensível lá hehe)

```sh
$ cd /tmp

$ dh -hd1 /tmp
dh: error: "debian/control" not found. Are you sure you are in the correct directory?

$ ls -laGh /tmp
total 108K
drwxrwxrwt 25 root  12K out  8 18:32 .
drwxr-xr-x 20 root 4,0K out  8 17:25 ..
srwxrwxr-x  1 cawe    0 out  8 18:29 app.atlascode-6706
prwx------  1 cawe    0 out  8 18:29 clr-debug-pipe-6789-40196-in
prwx------  1 cawe    0 out  8 18:29 clr-debug-pipe-6789-40196-out
prwx------  1 cawe    0 out  8 18:29 clr-debug-pipe-6887-40254-in
prwx------  1 cawe    0 out  8 18:29 clr-debug-pipe-6887-40254-out
drwx------  2 cawe 4,0K out  8 18:23 .com.google.Chrome.YmPWzo
srw-------  1 cawe    0 out  8 18:29 dotnet-diagnostic-6789-40196-socket
srw-------  1 cawe    0 out  8 18:29 dotnet-diagnostic-6887-40254-socket
drwxrwxrwt  2 root 4,0K out  8 18:23 .font-unix
-rw-------  1 cawe    0 out  8 18:23 gdm3-config-err-JivmGd
drwxrwxrwt  2 root 4,0K out  8 18:23 .ICE-unix
drwx------  2 cawe 4,0K out  8 18:32 minha-receita-badger-1731386749
drwx------  2 cawe 4,0K out  8 18:32 minha-receita-badger-3046353072
drwx------  2 cawe 4,0K out  8 18:32 minha-receita-badger-3790835015
drwxrwxr-x  2 cawe 4,0K out  8 18:29 node-jiti
drwx------  4 root 4,0K out  8 18:23 snap-private-tmp
drwx------  3 root 4,0K out  8 18:23 systemd-private-86c3df4e722c44b7b2b36736e6ac6b71-bluetooth.service-Qukoem
drwx------  3 root 4,0K out  8 18:23 systemd-private-86c3df4e722c44b7b2b36736e6ac6b71-colord.service-0JK4LT
drwx------  3 root 4,0K out  8 18:23 systemd-private-86c3df4e722c44b7b2b36736e6ac6b71-fwupd.service-2zNy5I
drwx------  3 root 4,0K out  8 18:23 systemd-private-86c3df4e722c44b7b2b36736e6ac6b71-ModemManager.service-uSQNeF
drwx------  3 root 4,0K out  8 18:23 systemd-private-86c3df4e722c44b7b2b36736e6ac6b71-power-profiles-daemon.service-mS1DiD
drwx------  3 root 4,0K out  8 18:23 systemd-private-86c3df4e722c44b7b2b36736e6ac6b71-switcheroo-control.service-Wtq0TY
drwx------  3 root 4,0K out  8 18:23 systemd-private-86c3df4e722c44b7b2b36736e6ac6b71-systemd-logind.service-juPx6c
drwx------  3 root 4,0K out  8 18:23 systemd-private-86c3df4e722c44b7b2b36736e6ac6b71-systemd-oomd.service-pbtg9b
drwx------  3 root 4,0K out  8 18:23 systemd-private-86c3df4e722c44b7b2b36736e6ac6b71-systemd-resolved.service-UPAvz1
drwx------  3 root 4,0K out  8 18:23 systemd-private-86c3df4e722c44b7b2b36736e6ac6b71-systemd-timesyncd.service-Ap2Q3R
drwx------  3 root 4,0K out  8 18:23 systemd-private-86c3df4e722c44b7b2b36736e6ac6b71-upower.service-Nvwnh7
drwxrwxrwt  2 root 4,0K out  8 18:23 .Test-unix
drwxrwxr-x  3 cawe 4,0K out  8 18:29 vscode-typescript1000
drwxrwxrwt  2 root 4,0K out  8 18:23 .X11-unix
drwxrwxrwt  2 root 4,0K out  8 18:23 .XIM-unix

$ cd ~/Code/minha-receita/data

$ dh -hd1 ~/Code/minha-receita/data/
dh: error: "debian/control" not found. Are you sure you are in the correct directory?

$ ls -laGh ~/Code/minha-receita/data/
total 5,9G
drwxrwxr-x  2 cawe 4,0K out  7 23:36 .
drwxrwxr-x 16 cawe 4,0K out  8 17:51 ..
-rw-r--r--  1 cawe  22K out  7 19:51 Cnaes.zip
-rw-r--r--  1 cawe 354M out  7 19:52 Empresas0.zip
-rw-r--r--  1 cawe  75M out  7 19:52 Empresas1.zip
-rw-r--r--  1 cawe  76M out  7 19:52 Empresas2.zip
-rw-r--r--  1 cawe  82M out  7 19:51 Empresas3.zip
-rw-r--r--  1 cawe  87M out  7 19:51 Empresas4.zip
-rw-r--r--  1 cawe  94M out  7 19:51 Empresas5.zip
-rw-r--r--  1 cawe  91M out  7 19:51 Empresas6.zip
-rw-r--r--  1 cawe  95M out  7 19:51 Empresas7.zip
-rw-r--r--  1 cawe  95M out  7 19:51 Empresas8.zip
-rw-r--r--  1 cawe  91M out  7 19:51 Empresas9.zip
-rw-r--r--  1 cawe 1,4G out  7 19:51 Estabelecimentos0.zip
-rw-r--r--  1 cawe 324M out  7 19:51 Estabelecimentos1.zip
-rw-r--r--  1 cawe 322M out  7 19:51 Estabelecimentos2.zip
-rw-r--r--  1 cawe 322M out  7 19:51 Estabelecimentos3.zip
-rw-r--r--  1 cawe 346M out  7 19:51 Estabelecimentos4.zip
-rw-r--r--  1 cawe 328M out  7 19:51 Estabelecimentos5.zip
-rw-r--r--  1 cawe 322M out  7 19:51 Estabelecimentos6.zip
-rw-r--r--  1 cawe 321M out  7 19:52 Estabelecimentos7.zip
-rw-r--r--  1 cawe 343M out  7 19:51 Estabelecimentos8.zip
-rw-r--r--  1 cawe 331M out  7 19:51 Estabelecimentos9.zip
-rw-rw-r--  1 cawe    0 out  4 16:26 .gitkeep
-rw-r--r--  1 cawe 1,2K out  7 19:51 Motivos.zip
-rw-r--r--  1 cawe  43K out  7 19:51 Municipios.zip
-rw-r--r--  1 cawe 1,5K out  7 19:51 Naturezas.zip
-rw-r--r--  1 cawe 2,7K out  7 19:51 Paises.zip
-rw-r--r--  1 cawe  980 out  7 19:51 Qualificacoes.zip
-rw-r--r--  1 cawe 152M out  7 19:51 Socios0.zip
-rw-r--r--  1 cawe  48M out  7 19:51 Socios1.zip
-rw-r--r--  1 cawe  47M out  7 19:51 Socios2.zip
-rw-r--r--  1 cawe  47M out  7 19:51 Socios3.zip
-rw-r--r--  1 cawe  47M out  7 19:51 Socios4.zip
-rw-r--r--  1 cawe  47M out  7 19:51 Socios5.zip
-rw-r--r--  1 cawe  48M out  7 19:51 Socios6.zip
-rw-r--r--  1 cawe  47M out  7 19:51 Socios7.zip
-rw-r--r--  1 cawe  47M out  7 19:51 Socios8.zip
-rw-r--r--  1 cawe  47M out  7 19:51 Socios9.zip
-rw-rw-r--  1 cawe 426K out  7 19:51 TABMUN.CSV
-rw-r--r--  1 cawe   10 out  7 19:46 updated_at.txt
```

**Comment by cuducos** [comment]
Nossa, me desculpe, digitei errado (corrigi ali, mas tarde demais): o comando é `du` (disk usage) não `dh`

**Comment by cuducos** [comment]
O que eu vejo, por enquanto:

```
drwx------  2 cawe 4,0K out  8 18:32 minha-receita-badger-1731386749
drwx------  2 cawe 4,0K out  8 18:32 minha-receita-badger-3046353072
drwx------  2 cawe 4,0K out  8 18:32 minha-receita-badger-3790835015
```

Esses arquivos são “banco de dados de chave e valor”, o Badger do link acima. Como eles estão praticamente vazios (4K não é nada), o que entendo é que o `minha-receita transform`:

1. tenta abrir os arquivos sócios/empresas/dados do simples, pois vemos [isso](https://github.com/cuducos/minha-receita/blob/0f6c2659b442e7652a4d0b381d3fac62db981055/transform/source.go#L135) nos logs
2. nada chega a ser escrito no Badger
3. sabemos que no código do Badger as fontes são criadas pois temos os arquivos temporários, e esse [código](https://github.com/cuducos/minha-receita/blob/0f6c2659b442e7652a4d0b381d3fac62db981055/transform/kv.go#L49) executou (temos os logs do primeiro item)
4. o que não sabemos é se o que não executou é a [leitura dos arquivos](https://github.com/cuducos/minha-receita/blob/0f6c2659b442e7652a4d0b381d3fac62db981055/transform/kv.go#L63-L82) ou a [escrita](https://github.com/cuducos/minha-receita/blob/0f6c2659b442e7652a4d0b381d3fac62db981055/transform/kv.go#L83-L93)

Quanto tempo você esperou nessa parte do terminal?

**Comment by cawecoy** [comment]
```sh
$ cd ~/Code/minha-receita/data

$ du -hd1 ~/Code/minha-receita/data/
5,9G	/home/cawe/Code/minha-receita/data/

$ cd /tmp

$ du -hd1 /tmp
4,0K	/tmp/.X11-unix
44K	/tmp/$Metadata$
28K	/tmp/minha-receita-badger-3046353072
28K	/tmp/minha-receita-badger-3790835015
28K	/tmp/minha-receita-badger-1731386749
4,0K	/tmp/.ICE-unix
24K	/tmp/node-jiti
4,0K	/tmp/.Test-unix
4,0K	/tmp/.font-unix
8,0K	/tmp/vscode-typescript1000
4,0K	/tmp/snap-private-tmp
4,0K	/tmp/.XIM-unix
4,0K	/tmp/.com.google.Chrome.YmPWzo
276K	/tmp
```

**Comment by cuducos** [comment]
Você tentou carregar uma [amostra” dos dados](https://github.com/cuducos/minha-receita/blob/main/CONTRIBUTING.md#amostra-dos-arquivos-para-testes) ao invés do banco de dados completo? Pode inclusive ir incrementando o `--max-lines` para testar com 1 milhão, 10 milhões etc.

**Comment by cawecoy** [comment]
@cuducos eu refiz o download dos dados e está funcionando. Não sei porque o comando `check` não identificou problema nos dados. Eu posso te enviar os dados que causou isso, caso você queira para fazer testes.

**Comment by cuducos** [comment]
Acontece : ) Esquenta não. Bom que resolveu.
