### ISSUE TITLE
Error: error writing venues to database: error during post load: unexpected EOF

### ISSUE THREAD

**Issue by cawecoy** [cuducos/minha-receita#249]
Olá! Alguém já viu esse erro e saberia informar como resolve-lo?

```sh
$ minha-receita transform -b 2048 -m 2
2024/10/10 06:41:20 Dropping table public.cnpj…
2024/10/10 06:41:20 Creating table public.cnpj…
2024/10/10 06:41:20 Loading Simples files…
2024/10/10 06:41:20 Loading Empresas files…
2024/10/10 06:41:20 Loading Socios files…
Processing base CNPJ, partners and taxes 100% |█████████████████████████████████████████████████████████████████████████████| (124759553/124759553, 101672 it/s)            
2024/10/10 07:01:54 Loading Estabelecimentos files…                                                                                                                         
Creating the JSON data for each CNPJ 100% |████████████████████████████████████████████████████████████████████████████████████| (62634863/62634863, 19521 it/s)            
Error: error writing venues to database: error during post load: 
unexpected EOF
```

Estou rodando sem Docker em ambiente local com essa configuração:

```sh
# ~180GB de armazenamento disponível
# ~9GB de RAM disponível, de um total de 16GB
# Memória SWAP de 32GB
# CPU i7-11800H
# Ubuntu 22.04.4
# PostgreSQL 14.13
```

**Comment by cuducos** [comment]
> `error during post load`

Isso quer dizer que todos os dados estão no banco de dados, o que é bom. Deu erro ao rodar a “rotina” de pós-carregamento dos dados — que basicamente é reerever os ínices. `EOF` quer dizer _end-of-file_, o que pode ser impreciso… talvez um erro na conexão com o PostgreSQL deu essa impressão ao banco de dados.

Para nã ter que carregar os dados novamente, você pode manualmente executar [o SQL](https://github.com/cuducos/minha-receita/blob/main/db/postgres/post_load.sql) diretamente no banco ; )

**Comment by cawecoy** [comment]
@cuducos mas o banco de dados está vazio:

```psql
minhareceita=# \list
                                   List of databases
     Name     |  Owner   | Encoding |   Collate   |    Ctype    |   Access privileges   
--------------+----------+----------+-------------+-------------+-----------------------
 minhareceita | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 | 
 postgres     | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 | 
 template0    | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 | =c/postgres          +
              |          |          |             |             | postgres=CTc/postgres
 template1    | postgres | UTF8     | en_US.UTF-8 | en_US.UTF-8 | =c/postgres          +
              |          |          |             |             | postgres=CTc/postgres
(4 rows)

minhareceita=# \c minhareceita 
You are now connected to database "minhareceita" as user "postgres".

minhareceita=# SELECT COUNT(id) FROM cnpj;
 count 
-------
     0
(1 row)

minhareceita=# select id from cnpj limit 1;
 id 
----
(0 rows)
```

**Comment by cuducos** [comment]
Provavelmente foi o banco que deu ruim então. Como o `SET LOGGED` acontece [só no final](https://github.com/cuducos/minha-receita/blob/0f6c2659b442e7652a4d0b381d3fac62db981055/db/postgres/post_load.sql#L22), há perda dos dados.

**Comment by cawecoy** [comment]
Tentei de novo e aconteceu esse problema:

```sh
error writing venues to database: error during post load: 
ERROR: could not extend file "base/16384/4714513.97": No space left on device (SQLSTATE 53100)
```

Eu passei uns arquivos pesados do meu notebook para um HD externo, consegui deixar 260GB livres, mas continua dando o erro `No space left on device (SQLSTATE 53100)`!

O que mais será que daria para eu fazer? Estou pensando seriamente em desistir de fazer isso em ambiente local e alugar um VPS.

**Comment by cawecoy** [comment]
Resolvi alugar uma VPS com 8 vCPU, 32GB de RAM e 400GB NVMe SSD, deu certo. Agradeço pelo suporte @cuducos !
