### ISSUE TITLE
Coluna com email

### ISSUE THREAD

**Issue by mtrentz** [cuducos/minha-receita#25]
Oi,

Gostaria de saber se existe um motivo em específico por não ser feito o parse dos emails dos contribuintes e tê-los adicionado na tabela final de empresas. 

Caso não tenha, seria possível adicionar esta informação visto que elas vem junto nos arquivos da receita?

Fora isso, obrigado pelo repo :)

**Comment by cuducos** [comment]
Opa, verdade! Sigo a mesma [linha de pensamento do Turicas sobre privacidade](https://github.com/turicas/socios-brasil#privacidade):

> Para garantir a privacidade, evitar SPAM e publicar apenas dados corretos, o script deleta/limpa algumas colunas com informações sensíveis ou incorretas. Essa é a forma padrão de funcionamento para não facilitar a exposição desses dados. 

Você acha que adicionando apenas no código (como comentário) é o suficiente ou acha que isso vale a pena constar no `README.md` e outros arquivos mais _human-readable_ do que o código-fonte em si?

**Comment by mtrentz** [comment]
Não sei dizer o quanto as pessoas que geralmente procuram por esse tipo de conteúdo têm interesse no email das pessoas. Talvez fosse bom adicionar no README.

Mas eu dei uma olhada no código e o que eu achei na verdade foi uma parte que remove alguns outros dados.

```
	// privacy issues
	deleteFromIndividuals := []int{
		11, // descricao_tipo_logradouro
		12, // logradouro
		13, // numero
		14, // complemento
		20, // ddd_telefone_1
		21, // ddd_telefone_2
		22, // ddd_fax
	}
```

Mas essa parte de email no caso é simplesmente pulada da parte que faz o parse (ficaria depois do FAX acho).

```
func parseCompany(l string) []string {
	cols := cleanLine([]string{
		l[3:17],    //  0 CNPJ
		l[17:18],   //  1 IdentificadorMatrizFilial
		l[18:168],  //  2 RazaoSocial
		l[168:223], //  3 NomeFantasia
		l[223:225], //  4 SituacaoCadastral
		l[225:233], //  5 DataSituacaoCadastral
		l[233:235], //  6 MotivoSituacaoCadastral
		l[235:290], //  7 NomeCidadeExterior
		l[362:367], //  8 CodigoNaturezaJuridica
		l[367:375], //  9 DataInicioAtividade
		l[375:382], // 10 CNAEFiscal
		l[382:402], // 11 DescricaoTipoLogradouro
		l[402:462], // 12 Logradouro
		l[462:467], // 13 Numero
		l[467:624], // 14 Complemento
		l[624:674], // 15 Bairro
		l[674:682], // 16 CEP
		l[682:684], // 17 UF
		l[684:688], // 18 CodigoMunicipio
		l[688:738], // 29 Municipio
		l[738:750], // 20 DDDTelefone1
		l[750:762], // 21 DDDTelefone2
		l[762:774], // 22 DDDFax
		l[889:891], // 23 QualificacaoDoResponsavel
		l[891:905], // 24 CapitalSocial
		l[905:907], // 25 Porte
		l[907:908], // 26 OpcaoPeloSimples
		l[908:916], // 27 DataOpcaoPeloSimples
		l[916:924], // 28 DataExclusaoDoSimples
		l[924:925], // 29 OpcaoPeloMEI
		l[925:948], // 30 SituacaoEspecial
		l[948:956], // 31 DataSituacaoEspecial
	})
```

Por isso fiquei na duvida e vim perguntar para ser sincero. Pois não sabia se era por questão de privacidade da informação ou só acharam que não fosse algo importante pro uso comum desse database.

**Comment by cuducos** [comment]
Existem duas preocupações (pelo menos) e duas estratégias, uma para cada preocupação:

| Preocupação | Estratégia |
|---|---|
| Não expor emails (evitar spam) | Não extrair o endereço de email do arquivo original da Receita Federal |
| Não expor dados sensíveis de pessoas físicas | Remover os dados sensíveis de empresas individuais (como não sabemos, na hora de extrair os dados do arquivo original da Receita Federal quais empresas são individuais, extraímos todos os dados e limpados depois) |

Isso explica as abordagens dos códigos que você destacou no seu comentário.
