### ISSUE TITLE
Instalação Local: Taxa de Atualização 

### ISSUE THREAD

**Issue by iruziky** [cuducos/minha-receita#250]
Quando eu fizer a instalação local do servidor, terei acesso aos dados atualizados em tempo real?
Exemplo: se uma empresa for aberta hoje, em pouco tempo ela estará na minha base de dados?

Eu conheci o projeto hoje mesmo, e gostaria de entender isso. Procurei algo sobre o tema  na documentação ou issues, mas não encontrei. Inclusive, não sei nem se é possível fazer isso que acabei de descrever.

Obrigado

**Comment by cuducos** [comment]
>
