### ISSUE TITLE
URL de download mudou

### ISSUE THREAD

**Issue by silvioes** [cuducos/minha-receita#258]
Referente ao problema do download que me referi no issue [253](https://github.com/cuducos/minha-receita/issues/253).

Acredito que a Receita talvez tenha alterado o link que ela disponibiliza esses dados, pelo link [https://dadosabertos.rfb.gov.br/CNPJ/](https://dadosabertos.rfb.gov.br/CNPJ/) que a aplicação usa caímos apenas em uma pagina de manutenção.

Mas acessando pelo [Portal de Dados abertos da Receita](https://dados.gov.br/dados/conjuntos-dados/cadastro-nacional-da-pessoa-juridica---cnpj) ele te encaminha pra um outro link, que seria o [https://arquivos.receitafederal.gov.br/cnpj/dados_abertos_cnpj/](https://arquivos.receitafederal.gov.br/cnpj/dados_abertos_cnpj/)

Eu tentei só mudar o link no arquivo [download/federal_revenue.go](https://github.com/cuducos/minha-receita/blob/main/download/federal_revenue.go) mas seguiu com erro no download, então se a Receita mudou o link do espelho de dados e não funcionou só apontando pro novo, imagino que tenha mais mudanças e como ainda não conheço tão bem o código achei melhor criar essa issue pra você dar uma olhada quando puder.

**Comment by cuducos** [comment]
> Eu tentei só mudar o link no arquivo [download/federal_revenue.go](https://github.com/cuducos/minha-receita/blob/main/download/federal_revenue.go)

Qual link? [Esse](https://github.com/cuducos/minha-receita/blob/3865a642f42f8a32630b8f99241756a4b0a892f2/download/federal_revenue.go#L25) ou [esse](https://github.com/cuducos/minha-receita/blob/3865a642f42f8a32630b8f99241756a4b0a892f2/download/federal_revenue.go#L30)? O correto é o segundo.

**Comment by silvioes** [comment]
Fiz o teste alterando o segundo mesmo `federalRevenueURL `

De
`federalRevenueURL = "https://dadosabertos.rfb.gov.br/CNPJ/dados_abertos_cnpj"`

Para
`federalRevenueURL = "https://arquivos.receitafederal.gov.br/cnpj/dados_abertos_cnpj"`

**Comment by cuducos** [comment]
_Quase_ funcionou. `go run main.go urls` lista as URLs corretamente, mas `download` ainda tem algum outro bug, né?

**Comment by cuducos** [comment]
Opa, não… `connection reset by peer` (erro do servidor da Receita Federal). É só essa linha mesmo. Quer abrir um PR?

**Comment by silvioes** [comment]
Então é só trocar o link da `federalRevenueURL` pra esse novo mesmo? Se for isso eu queria fazer sim.

**Comment by kenaioz** [comment]
![image](https://github.com/user-attachments/assets/190ddf21-ab8f-4180-982b-d30a76d58161)

Vou fazer a alteração pela minha conta pessoal, essa outra é a minha corporativa.

**Comment by cuducos** [comment]
Você não vai conseguir fazer um `git push` para o meu repositório. O caminho é [fazer um _fork_](https://github.com/cuducos/minha-receita/fork) na tua conta, faz o `git push` para lá, e de lá abre um _Pull Request_ para cá. Esse [repositório explica com detalhes](https://github.com/brazilian-utils/brutils-python/blob/main/CONTRIBUTING.md#4-fa%C3%A7a-um-fork-do-projeto) ; )

**Comment by kenaioz** [comment]
PR criado

[PR #259](https://github.com/cuducos/minha-receita/pull/259)
