### ISSUE TITLE
Falha no carregamento dos dados de `Empresas*.zip`

### ISSUE THREAD

**Issue by iago-effting** [cuducos/minha-receita#269]
Estou utilizando a API e o campo `razao_social` esta retornando string vazia em todos os casos.

Esse cenário acontece diretamente no recurso disponibilizado na doc da no endpoint: API https://minhareceita.org/40.117.287/0001-59

![image](https://github.com/user-attachments/assets/ef41f0ae-8d7c-40df-9a93-21c4517d5238)

Gostaria de saber se nao será mais exibido ela, ou se existe algum problema que será resolvido

**Comment by murilodacios** [comment]
Olá, estou com o mesmo problema hoje.

**Comment by eduardo-gouvea-barreto** [comment]
O mesmo acontece comigo. Para que passou a acontecer desde 19/12/2024

**Comment by Marcelo-maga** [comment]
Mesmo problema aqui

**Comment by cuducos** [comment]
Obrigda por reportar o _bug_. Vou investigar : )

**Comment by cuducos** [comment]
Nenhum dado do `Empresas*.zip` foi carregado no banco de dados: porte, razão sozial, natureza jurídica, e ente federativo. A estrutura do CSV parece a mesma, e os dados constam no CSV. Vou tentar re-importar os dados — leva cerca de 2h.

**Comment by rasrenan** [comment]
@cuducos caso você esteja mexendo nisso por agora, o QSA também passou a retornar vazia da mesma forma que a Razão Social e outros itens, como o booleano se a empresa pertence ao Simples Nacional ou não. Obrigado

**Comment by cuducos** [comment]
Regularizado : ) Obrigada mais uma vez a todo mundo por avisar 💜
