### ISSUE TITLE
Mudar API para aceitar GET ao invés de POST

### ISSUE THREAD

**Issue by cuducos** [cuducos/minha-receita#29]
De acordo com https://github.com/cuducos/minha-receita/issues/27#issuecomment-773717155, não há necessidade de manter a interface como POST.

**Comment by rodolfolottin** [comment]
Opa! Posso tocar essa? Tô nos meus passos iniciais com Golang e acho que seria um desafio legal 😄

**Comment by cuducos** [comment]
Claro 💜

**Comment by cuducos** [comment]
Tu já deve estar no meio do caminho, mas um _roadmap_ que eu sugiro:
- [ ] Alterar [teste que espera `405` de `GET`](https://github.com/cuducos/minha-receita/blob/b38a94164a1a163edf089b72c0fa3eb13f59e0ed/api/api_test.go#L62) para `POST` 
- [ ] Alterar [test cases com método esperado](https://github.com/cuducos/minha-receita/blob/b38a94164a1a163edf089b72c0fa3eb13f59e0ed/api/api_test.go#L67-L108) (não esquecer de trocar `POST` por `GET` nas mensagens de erro _Essa URL aceita apenas o método POST_)
- [ ] Utilizar o `request.URL.Path` para extrair o valor do CNPJ ([esse padrão pode ser útil](https://golang.org/pkg/net/http/#ServeMux.Handle) para substituir [essa lógica](https://github.com/cuducos/minha-receita/blob/b38a94164a1a163edf089b72c0fa3eb13f59e0ed/api/api.go#L53-L58))
- [ ] Atualizar documentação em `docs/cliente.md`

**Comment by rodolfolottin** [comment]
Muito obrigado pela sugestão de roadmap! 

Acabei não conseguindo evoluir muito com essa contribuição, mas planejo dedicar um tempo nos próximos dias pra isso

**Comment by cuducos** [comment]
Sem problemas. Se eu puder ajudar de alguma forma, só dizer ; )

**Comment by cuducos** [comment]
Discussão movida para #35
