### ISSUE TITLE
ERROR: relation "idx_empresa_cnpj" already exists

### ISSUE THREAD

**Issue by jessicapaz** [cuducos/minha-receita#3]
O erro é esse aqui:

![JEfD4Iuq](https://user-images.githubusercontent.com/20428941/61949847-7ed4df00-af82-11e9-860c-6af0444aa373.jpg)

**Comment by cuducos** [comment]
Oi @jessicapaz. Quando for colar o erro, evite colar, por favor, _print screen_. Isso dificulta busca. Se alguém vier procurar no GitHub ou Google por "relation … already exist" por exemplo, não vai achar pois você não incluiu isso como texto, apenas como imagem. Você pode editar teu post e incluir o erro como texto — recomendo, é bem melhor para o projeto.

Dito isso, a linha `ERROR relation "idx_empresa_cnpj" already exists` dá a entender que tu está tentando criar um índice que já exsite — em outras palavras, ao invés de rodar o `docker-copose up feed` em um banco de dados limpo, zerado tu está tentando rodar ele em um banco de dados que já existe. Isso não vai funcionar. Tente começar de um banco no PostgreSQL sem nenhuma tabela ou índice e veja se o erro persiste.
