### ISSUE TITLE
Erro ao tentar rodar o projeto: Could not connect to PostgreSQL

### ISSUE THREAD

**Issue by rodolfolottin** [cuducos/minha-receita#32]
Olá!

Seguindo os passos descritos descritos em https://docs.minhareceita.org/instalacao/ estou tendo o seguinte erro ao tentar rodar o projeto:

```
[I] minha-receita (docs/env-setup): docker-compose run --rm minha-receita
Creating network "minha-receita_default" with the default driver
Creating minha-receita_postgres_1 ... done
Creating minha-receita_minha-receita_run ... done
2021/02/24 11:32:24 No POSTGRES_SCHEMA environment variable found, using public.
Could not connect to PostgreSQL: dial tcp 172.20.0.2:5432: connect: connection refused
```

O mesmo acontece caso rode com:

```
docker-compose up
```

Devo especificar a variável de ambiente POSTGRES_SCHEMA ou o schema public já [deveria funcionar](https://github.com/cuducos/minha-receita/blob/main/db/postgres.go#L90-L93)?

**Comment by cuducos** [comment]
O Postgres não está acessível para a Minha Receita apenas ou em lugar nenhum?

**Comment by cuducos** [comment]
Dado que o autor conseguiu rodar o projeto (dado o PR #35), acredito que essa _issue_ seja obsoleta. Se errei no julgamento, podem puxar minha orleha e reabrir : )
