### ISSUE TITLE
Erro no valor do capital social

### ISSUE THREAD

**Issue by galodoidobsb** [cuducos/minha-receita#33]
Bom dia!
Parabéns pelo projeto, muito bacana.
Percebi que o valor do capital social está vindo sempre multiplicado por um fator de 100x (para qualquer CNPJ).
Originalmente o dado é do tipo decimal/float, mas no projeto ele é convertido para inteiro e pode estar incorporando os dois zeros após a vírgula.

Para fins de comparação, deixo aqui o valor retornado para o capital social do CNPJ e o que consta em outros mecanismos de consulta (e também o que consta na base de dados da receita):

`
    "cnpj": "10942831000136",
    "identificador_matriz_filial": 1,
    "descricao_matriz_filial": "Matriz",
    "razao_social": "COMERCIAL VANGUARDEIRA EIRELI",
    "nome_fantasia": "VANGUARDEIRA",
    "capital_social": 6220000,
`

Informações de Registro
CNPJ: 10.942.831/0001-36 - 10942831000136
Razão Social: Comercial Vanguardeira Eireli
Nome Fantasia: Vanguardeira
Data da Abertura: 29/06/2009
**Capital Social: R$ 62.200,00**
Tipo: MATRIZ
Situação: ATIVA
Fonte: https://cnpj.biz/10942831000136

Obrigado (:

**Comment by cuducos** [comment]
Muito obrigado, @galodoidobsb! Bela contribuição encontrando esse bug 💜 

Caso interesse, corrigi o _parser_  (_hotfix_ 70f0eeb, e depois 7f83bf9) e subi os dados novos para produção : )

**Comment by galodoidobsb** [comment]
Por nada meu querido @cuducos ! Feliz em poder contribuir, muito legal o projeto!
