### ISSUE TITLE
sqlite

### ISSUE THREAD

**Issue by Slender1808** [cuducos/minha-receita#39]
seria possível ter versão em sqlite ?

**Comment by cuducos** [comment]
Não é o foco desse projeto. Mas a versão CSV, mais a [Rows](https://github.com/turicas/rows) resolvem isso para ti facinho, facinho.

**Comment by Slender1808** [comment]
> Não é o foco desse projeto. Mas a versão CSV, mais a [Rows](https://github.com/turicas/rows) resolvem isso para ti facinho, facinho.

Seria top de receita federal fornecer os dados SQLite ao invés csv
