### ISSUE TITLE
OSError: CRC check failed

### ISSUE THREAD

**Issue by novaeslucas** [cuducos/minha-receita#4]
Olá,

Estou tentando subir a aplicação e está apresentando um erro ao carregar o container feed com 'docker-compose up feed'.

1. Os arquivos cnae, socio, empresa e cnae (xlsx) estão na pasta 'minha-receita/data';
2. Estou subindo a aplicação em uma máquina virtual, ubuntu 18.04 lts, 60gb de hd, 4 gb de ram.

Já fiz várias tentativas e ainda sem sucesso.

![Sem Título](https://user-images.githubusercontent.com/61071/63230607-7c624f80-c1e5-11e9-9aaa-5ab2c009cd08.jpeg)

**Comment by cuducos** [comment]
Oi @novaeslucas. Vou recomendar, primeiro, o que recomendei na #3 

> Quando for colar o erro, evite colar, por favor, print screen. Isso dificulta busca. Se alguém vier procurar no GitHub ou Google por "relation … already exist" por exemplo, não vai achar pois você não incluiu isso como texto, apenas como imagem. Você pode editar teu post e incluir o erro como texto — recomendo, é bem melhor para o projeto.

Dito isso, esse erro ocorre dentro da `pgimport` da `rows`. Então marco @turicas aqui para perguntar se ele já viu isso correndo nessa funcionalidade… pois aqui não consegui reproduzir.

**Comment by turicas** [comment]
@novaeslucas possivelmente os arquivos que você está utilizando estão corrompidos ou não estão compactados em gzip (que é o esperado nesse caso). Os arquivos mais atuais para esse dataset disponíveis para download no Brasil.IO estão em:
- https://data.brasil.io/dataset/socios-brasil/empresa.csv.gz
- https://data.brasil.io/dataset/socios-brasil/socio.csv.gz
- https://data.brasil.io/dataset/socios-brasil/cnae-secundaria.csv.gz
O arquivo contendo o sha1 sum de cada um deles (para que você verifique se não ficou corrompido no download) está disponível em: https://data.brasil.io/dataset/socios-brasil/SHA1SUMS

**Comment by novaeslucas** [comment]
@cuducos Ok. seguirei a recomendação.

@turicas Eu pensei que fosse isso tbm, porém antes de abrir essa issue eu descompactei os arquivos, funcionou normalmente e importei esses csv's num postgresql local. Só por via das dúvidas vou fazer o download e tentar novamente.

**Comment by cuducos** [comment]
Fechando essa _issue_ por:
* inatividade
* alta probabilidade do problema não ser nesse repositório
* alta probabilidade do problema não ser na `rows` tb (que seria indiretamente relacionado a esse repositório)

Caso o erro persista, é só dar um oi aqui que reabrimos e continuamos o papo, ok?
