### ISSUE TITLE
Encode de carácteres especiais no Safari

### ISSUE THREAD

**Issue by avelino** [cuducos/minha-receita#41]
```json
{"message":"CNPJ nÃ£o enviado na requisiÃ§Ã£o GET."}
```

ao acessar o endpoint com verbo GET body retorna com carácteres “quebrado”

![E202738E-AC6A-4CF9-9AAE-3ABD98D6984C](https://user-images.githubusercontent.com/31996/129548492-866066c1-1291-4ec8-8da3-9ad88ec93097.jpeg)

**Comment by cuducos** [comment]
Hum… me parece algo do cliente, né?

Pela tua imagem, tais no iOS e no Safari — essa combinação aqui deu o mesm o erro. Firefox Focus no iOS, idem.

Mas no masOS e no Debian, tanto no `curl` quanto no Firefox os caracteres aprecem de boa. De estalo, não sei o que pode ser. Qualquer ajuda é bem vinda : )

**Comment by cuducos** [comment]
Na aplicação utilizamos [`w.Header().Set("Content-type", "application/json")`](https://github.com/cuducos/minha-receita/blob/1ad663696f5c20176e3abb4f4617342705a5df1e/api/api.go#L69) nas respostas HTTP.

Pelo o que li, utilizar `application/json; charset=utf-8` seria redundante e desnecessário já que UTF-8 é o _encoding_ padrão de JSON ([item 3](https://www.ietf.org/rfc/rfc4627.txt)).

**Comment by victtorvpb** [comment]
Realmente parece ser encoding do navegador, o safari por padrão é `Ocidental Iso Latino 1`, a resposta da API está retornando corretamente.

<img width="1425" alt="Captura de Tela 2022-01-28 às 09 58 50" src="https://user-images.githubusercontent.com/4712774/151551317-056d9b9e-6ab9-4773-aff4-fe1ba9cacc06.png">
a

**Comment by brunbs** [comment]
Não seria possível usar sinônimos que não possuem caracteres especiais para evitar isso? Ou há outras formas?

**Comment by cuducos** [comment]
Possível seria, @brunbs — mas isso seria “errado” (assim mesmo, entre aspas). O procedimento, do lado do servidor me parece correto: o _encoding_ utilizado bate com o _encoding_ informado no cabeçalho (levando em conta o que [destaquei antes](https://github.com/cuducos/minha-receita/issues/41#issuecomment-900561522)).

O ponto é que tua sugestão não resolve o problema, ela foge do problema — eu eu não acho que o uso via navegador é o foco do projeto. Então prefiro não fazer “gambiarras” e focar no problema (que ainda ninguém parece ter entendido)…

Interessante o ponto do @victtorvpb: tudo bem o Safari ter um padrão, mas pq o Safari desrespeita o informado no cabeçalho e definido na RFC do JSON? Se for esse o caso mesmo, é um bug do Safari e não do projeto. Como o foco do projeto não é uso via Safari, preferiria simplesmente ignorar.

**Comment by cuducos** [comment]
@jbiason deu um palpite interessante [no Twitter](https://twitter.com/juliobiason/status/1489318490205040642):

> Eu repliquei o problema, usando Epiphany (baseado no WebKit).
>
> Notei uma coisa: ele não faz o “parse” do JSON, apenas mostra o conteúdo da resposta, como um punhado de _bytes_.
> Então, eu acho que o problema do Safari é que ele não tem um _parser_ de JSON: ele só vê _bytes_.

Por tudo conversado aqui, me parece a hipótese mais contundente. Como isso é uma questão (bug? hehehe 😈 ) de um navegador específico, e como o foco da API não é o uso via navegador, vou fechar essa _issue_.

Quem chegar com alguma notícia nova, algo que mude esse cenário, sinta-se em casa para reabri-la 💜
