### ISSUE TITLE
Site estático no / explicando como consumir a API

### ISSUE THREAD

**Issue by avelino** [cuducos/minha-receita#42]
Sei que temos o README, mas pensando em deixar o uso do projeto minha-receita mais amigável seria importante ter uma página (html) falando sobre o projeto e como consumir a api

**Comment by cuducos** [comment]
Acho que a pergunta é: como dar mais visibilidade ao https://docs.minhareceita.org ?

Faz sentido?

**Comment by cuducos** [comment]
Complementando, no `README.md` existem links para a documentação em dois lugares:
![Pasted_Image_2021-08-16__8_34_PM](https://user-images.githubusercontent.com/4732915/129645625-35b2efec-c624-4391-ba97-3e3c708fa370.png)

Não sei se:

* são os melhores lugares
* se é esse conteúdo do [`docs.minhareceita.org`](https://docs.minhareceita.org) que melhor responde a essa _issue_
* se vale a pena colocar, na mensagem da resposta do `GET /` algo como: `{"message":"CNPJ não enviado na requisição GET. Visite https://docs.minhareceita.org para mais detalhes de como utilizar essa API."}

O que acham?

**Comment by cuducos** [comment]
Ou… `GET /` poderia ser um `HTTP 302` para [`docs.minhareceita.org`](https://docs.minhareceita.org)?

**Comment by avelino** [comment]
dado que não existe body válido para /, acredito que 302 DOCs seja a melhor solução
