### ISSUE TITLE
Docker Hub support

### ISSUE THREAD

**Issue by sibelius** [cuducos/minha-receita#49]
does it make sense to provide docker images directly on dockerhub?

we could automate this workflow using github actions

**Comment by sibelius** [comment]
I wanna to make it easy to run on premise version of this api

if this does not make sense, feel free to close

**Comment by cuducos** [comment]
So, basically, you're saying that sharing the container image in Docker Hub is more valuable to allow people to run in production than the binary (as I initially suggested)? If, so, can you clarify why.

**Comment by cuducos** [comment]
Ok, great! Take your time then… once you identify the changes needed, feel free to update the issue and we check how to add that without making maintainability more complex :purple_heart:

**Comment by sibelius** [comment]
I won't be able to pursue this right now, so I'm gonna close right now

**Comment by cuducos** [comment]
Re-opening, since @sibelius might not be the only one able to help with Docker hub support 💜

**Comment by cuducos** [comment]
Closed by 4f01084

Docker image is now published [in GitHub registry](https://github.com/cuducos/minha-receita/pkgs/container/minha-receita). For example:

```console
docker pull ghcr.io/cuducos/minha-receita:main
```
