### ISSUE TITLE
API para buscar CNAES

### ISSUE THREAD

**Issue by mauchigen** [cuducos/minha-receita#7]
Boa tarde, tudo bem?

Primeiramente gostaria de agradecer pela disponibilizacao da API.

Gostaria de utilizar a API para buscar um CNAE ao inves de um CNPJ, e como retorno da consulta gostaria da lista das empresas que possuem o mesmo CNAE.

Como tenho pouco conhecimento com docker/programacao nao sei como adaptar. Poderia me auxiliar?

Obrigado,

**Comment by cuducos** [comment]
Oi @mauchigen,

Obrigado pela mensagem e pela boa ideia de nova funcionalidade!

Você pode contar um pouco mais do teu caso de uso específico? Me explico: uma busca como essa com certeza sobrecarregaria o servidor, pois seriam muitos resultados a retornar… por exemplo, contando apenas o campo _CNAE Fiscal_ (atividade principal_), tanto _Comércio varejista de artigos do vestuário e acessórios_ quanto __Atividades de organizações políticas_ gerariam uma listagem de mais de 2 milhões de empresas. Em média, cada CNAE (ainda contanto apenas atividade principal) tem 32 mil empresas.

Claro que, tecnicamente é viável implementar isso, com paginação nas respostas. Mas, pensando em uma melhor experiência de uso, o melhor seria entender como você pretende lidar com esses resultados longos: tens algum filtro em mente além de CNAE? Qual ordenação faria sentido? Essas e outras perguntas são necessárias para que essa API entregue, de fato, algo útil, eu acho : )

**Comment by mauchigen** [comment]
Obrigado @cuducos pela rápida resposta!

Para contextualizar, tenho estudando a geração de resíduos perigosos, principalmente pelas indústrias, mas também gerado através de comerciantes e importadores (buscando traçar o caminho da logística reversa de resíduos).

Como eu já tenho uma base de CNAEs que sei que geram resíduos perigosos em seus processos produtivos por exemplo:

Seção: | C | INDÚSTRIAS DE TRANSFORMAÇÃO
-- | -- | --
Divisão: |   | 20 FABRICAÇÃO DE PRODUTOS QUÍMICOS
Grupo: |   | 20.7 Fabricação de tintas, vernizes, esmaltes, lacas e produtos afins
Classe: |   | 20.71-1 Fabricação de tintas, vernizes, esmaltes e lacas
Subclasse: |   | 2071-1/00 Fabricação de tintas, vernizes, esmaltes e lacas

Eu sei que essa subclasse de CNAE é um possível gerador de resíduos perigosos.

Desta forma utilizaria a API para buscar e alocar pelo endereço/município os tipos de resíduos dos seus possíveis geradores (empresas), e jogaria esses dados para uma plataforma de mapeamento.

Esta segunda etapa de mapeamento é minha área de atuação, por isso para estruturar e colocar a API para funcionar é novo para mim. Eu já consegui utilizar algumas apis seguindo estritamente alguns tutoriais bem detalhados, visto que programação não é meu forte.

**Comment by cuducos** [comment]
Perfeito… vamos fazer assim: deixamos esse tópico aqui para regsitro e no tempo do código aberto pode ser que eu, ou mais alguém, implemente!

Mas se tu precisa de algo específico assim, posso te ajudar sem ser criando a funcionalidade. Me manda uma mensagem (mesmo nome de usuário que aqui no Telegram, GitHub e Instagram), ou email (tem [no meu site](https://cuducos.me), me conta mais dos teus estudos e posso ver de gerar essa listagem pra ti.

**Comment by cuducos** [comment]
Fechado por inatividade.
