### ISSUE TITLE
Criar uma lógica de checksum para validar os arquivos

### ISSUE THREAD

**Issue by renatosuero** [cuducos/minha-receita#75]
Discutindo com o @cuducos sobre isso, a sugestão dele foi algo como `minha-receita checksum`:

- baixa (isso pode ser o comando `download` mesmo)
- confere se número de arquivos baixados bate com o `--urls-only`
- confirma [se os arquivos estão ok](https://docs.minhareceita.org/servidor/#verificacao-dos-downloads)
- gera o arquivo _checksum_

Isso pode facilitar dois cenários:
- criação e manutenção de um _mirror_ dos dados
- comparação com os arquivos da Receita Federal **caso** eles adotem _checksum_ um dia

**Comment by renatosuero** [comment]
if fosse confiável poderia ser essa informação no site https://www.gov.br/receitafederal/pt-br/assuntos/orientacao-tributaria/cadastros/consultas/dados-publicos-cnpj
<img width="485" alt="Screen Shot 2021-12-17 at 13 59 28" src="https://user-images.githubusercontent.com/1093214/146580656-9f69b661-9b78-45ce-9bd8-d6a4b2135ca2.png">

**Comment by vmesel** [comment]
Pergunta boba aqui de quem tá interessado em contribuir: o checksum precisa estar salvo em algum lugar para podermos comparar, não?

O que quero dizer: precisamos bater em alguma API para sabermos se os dados que baixamos são os mesmos que estão sendo disponibilizados pela receita, correto?

Ou estariamos fazendo a parte de checksum para poder identificar quando tivermos um update? @cuducos

**Comment by cuducos** [comment]
> Pergunta boba aqui de quem tá interessado em contribuir: o checksum precisa estar salvo em algum lugar para podermos comparar, não?

Sim, localmente no diretório `data/` (padrão) ou no passado por `--directory` no CLI.

---

> O que quero dizer: precisamos bater em alguma API para sabermos se os dados que baixamos são os mesmos que estão sendo disponibilizados pela receita, correto?

Não. Como a Receita Federal não disponibiliza _checksum_, não há o porquê. Repare que os cenários de uso são futuros e hipotéticos hahaha…

     

> Isso pode facilitar dois cenários:
> 
>     criação e manutenção de um mirror dos dados
>     comparação com os arquivos da Receita Federal caso eles adotem checksum um dia

---

> Ou estariamos fazendo a parte de checksum para poder identificar quando tivermos um update?

Também não. Como a Receita Federal não disponibiliza _checksum_, isso não seria possível.

O caso de uso seria, vamos supor:
* eu baixo os dados e crio um mirror
* tu baixa um arquivo do meu mirror
* tu pode calcular o checksum do que você baxou com o que está no meu mirror para ver se o teu download está ok

**Comment by vmesel** [comment]
Então, teremos os dados do servidor (`cuducos.not.at.home:80`) e os dados de um branch local (`vmesel.not.at.the-office:80:/data/tmp/...`). Para isso a gente precisa ter duas coisas, no meu entendimento:

 - [ ] Um endpoint na API que permita a leitura do `checksum` desses arquivos no host
 - [ ] Um endpoint para download dos arquivos do mirror
 - [ ] Uma função que calcula o `checksum` do arquivo local
 - [ ] Uma função de comparação de um host que a pessoa define ou o default do minha-receita.

Correto?

**Comment by cuducos** [comment]
> Então, teremos os dados do servidor

Não não.

Não tem servidor, não tem cliente. Tudo acontece local.

Terminou o download?
Gera os arquivos de _checksum_. Fim.

**Comment by vmesel** [comment]
Ok! Entendi agora! Tks

**Comment by cuducos** [comment]
Isso pode ser incorporado (por padrão) no [`check`](https://docs.minhareceita.org/servidor/#verificacao-dos-downloads), por exemplo… aí só geraria _checksum_ de arquivos que forem verificados. 

Aí podia ter `check --skip-checksum` caso a pessoa não queria gerar.

**Comment by eu-ovictor** [comment]
Gostaria de atuar nessa issue. Lendo a conversa deu a entender que tem dois casos de uso pro `checksum`:
- Criação. Após os arquivos terem sidos baixados, e a integridade deles ter sido conferida pelo comando `check`, os arquivos `checksum` tem que ser criados. Aqui imagino um pós download das fontes da receita federal.
- Validação. Dado arquivos que eu tenho (incluindo o de `checksum`), eu preciso conferir se o que eu tenho bate com o `checksum` existente. Aqui imagino um pós download de algum mirror existente.

Minha idéia é além de integrar  o `checksum` no comando `check`, ter um comando específico com dois subcomandos, ficando algo tipo: `minha-receita checksum create` e `minha-receita checksum validate (ou check)`

Algumas dúvidas além:
- O `checksum` é para cada arquivo dentro do diretório? Ou é apenas um arquivo para o diretório inteiro? 
- Queremos permitir o uso de diferentes algoritmos? Ou vamos usar um default (md5 da vida ou coisa assim)? Se quisermos permitir, podemos incluir uma flag `--alg` nos comandos.

**Comment by cuducos** [comment]
> Minha idéia é além de integrar  o `checksum` no comando `check`, ter um comando específico com dois subcomandos, ficando algo tipo: `minha-receita checksum create` e `minha-receita checksum validate (ou check)`

Achei confuso. O que acha de simplificar e apenas ter o `minha-receita checksum create` e `minha-receita checksum check`?

Ou, ser tudo no `check` (a semântica ajuda aí)?

* `minha-receita check zip-integrity` (que seria a lógica atual do `minha-receita check`)
* `minha-receita check checksum create`
* `minha-receita check checksum check`

> O `checksum` é para cada arquivo dentro do diretório? Ou é apenas um arquivo para o diretório inteiro?

Um por arquivo baixado.

> Queremos permitir o uso de diferentes algoritmos? 

Talvez, mas diria que não agora. Vamos começar com o `md5` simplão mesmo. Se surgir um caso de uso diferente, é mais fáicl pensar nisso depois que a funcionalidade já estiver implementada.
