### ISSUE TITLE
Salvar informação da data dos datasets originais

### ISSUE THREAD

**Issue by cuducos** [cuducos/minha-receita#93]
No [site oficial da Receita Federal](https://www.gov.br/receitafederal/pt-br/assuntos/orientacao-tributaria/cadastros/consultas/dados-publicos-cnpj) existe a informação sobre quando os dados foram atualizados:

![Pasted_Image_2022-01-04__11_02_AM](https://user-images.githubusercontent.com/4732915/148087561-b89d3210-5720-4957-82c0-163a8228cd3a.png)

Seria interessante essa informação fazer parte do ETL e da API.

Uma **sugestão** de implementação (depende de #95):

No comando `download` já lemos essa página para extrair as URLs dos arquivos CSV, então poderíamos identificar essa data e salvá-la junto com os dados. No PostgreSQL esse comando pode ser uma query única que ~~cria uma tabela (caso ela não exista, apenas) e~~ faz _upsert_ no único registro dessa tabela com o conteúdo desse arquivo.

- [x]  Criar `last_update.txt` já no formato `YYYY-MM-DD` no comando `download` 413fbf2
- [ ] Adiciona o método `SaveLastUpdate() error` na interface `transform.database`
- [ ] Adicionar a tabela na interface com o PostgreSQL, incluindo edições do `create.sql`, `drop.sql` e o novo método, algo como `SaveLastUpdate(date string)`
- [ ] Salvar essa informação no banco de dados no comando `transform`
- [ ] Criar um _endpoint_ `/last_updated` na API
- [ ] Documentar o _endpoint_ em `docs/cliente.md`

---

Exemplos de SQL:

```sql
CREATE TABLE IF NOT EXISTS public.last_update (
    id INTEGER PRIMARY KEY,
    last_updated_on date
);

INSERT INTO public.last_update (id, last_updated_on)
VALUES(1, '2021-10-20')
ON CONFLICT (id)
DO UPDATE SET last_updated_on = '2021-10-20';
```

Exemplo de resposta para `GET /last_updated`

```json
{"last_updated_on": "2021-10-20"}
```

**Comment by andidevel** [comment]
Se não se importar, posso tentar fechar essa issue.

**Comment by cuducos** [comment]
Coisa linda, @andidevel! Como posso ajudar?

Vou tentar ajudar com palpites:
* hoje cedo editei a descrição da _issue_ pois mudei de ideia em alguns pontos, vale reler
* acho que essas alterações podem vir em PRs menores (talvez um apenas implementando a parte do comando `download` e criação do `last_update.txt`; depois outro com a parte de banco de dados; e, por fim, endpoint na API e documentação)
* acho que vale fazer o PR com base na branch `batch` (candidata a ser _mergeada_ na `dev` logo mais)
* na branch `batch` temos a documentação mais atualizada (talvez valha a pena verificar [`docs/instalacao.md`](https://github.com/cuducos/minha-receita/blob/batch/docs/instalacao.md) e [`docs/servidor.md`](https://github.com/cuducos/minha-receita/blob/batch/docs/servidor.md), bem como o [`CONTRIBUTING.md`](https://github.com/cuducos/minha-receita/blob/batch/CONTRIBUTING.md) dessa _branch_ ao invés da `main`)
* a `dev`, nos próximos dias, deve ser atualizada com a _branch_ `batch` via #92 e #95

**Comment by andidevel** [comment]
Ótimo!!! Vai ser um aprendizado. Vou atualizar o meu fork do projeto e seguir as suas dicas.

Valeu!

**Comment by andidevel** [comment]
Desculpe, mas estou tendo uma dificuldade para montar o ambiente de desenvolvimento, ao usar o `docker-compose build`, obtenho o seguinte erro:
```
--- FAIL: TestPostgresDB (0.00s)
    postgres_test.go:15: expected a posgres uri at TEST_POSTGRES_URI, found nothing
```
Inclusive já tentei configurar essa variável de ambiente diretamente no `docker-compose.yml`:
```yml
  minha-receita:
    environment:
      - TEST_POSTGRES_URI="postgres://minhareceita:minhareceita@localhost:5555/minhareceita?sslmode=disable"
    build: .
    ports:
      - 8000:8000
    volumes:
      - ./data:/mnt/data
```
Sem sucesso.
 
Está faltando fazer alguma outra coisa aqui no meu ambiente, ou será que tem a ver com a minha versão do docker/docker-compose?

Docker version **20.10.7**

docker-compose version **1.25.0**

Por hora estou utilizando somente os bancos de dados via docker e antes de rodar os testes fiz:
```
export TEST_POSTGRES_URI="postgres://minhareceita:minhareceita@localhost:5555/minhareceita?sslmode=disable"
```
Que funcionou como o esperado.

Se alguém tem alguma dica de como fazer funcionar diretamente com `docker-compose build`, ficaria agradecido.

**Comment by cuducos** [comment]
Pegou uma bela barbeiragem minha. Pode tirar a parte de `go test` do `Dockerfile` – inclusive abri a #96 para isso ; )

**Comment by cuducos** [comment]
> Por hora estou utilizando somente os bancos de dados via docker 

Ou… não precisa de `docker build` se vais usar o banco de dados via Docker. Como tem no `CONTRIBUTING.md` só `docker-compose up -d postgres_test` já resolve.

**Comment by andidevel** [comment]
Algumas considerações:

Acessando a página [oficial da Receita](https://www.gov.br/receitafederal/pt-br/assuntos/orientacao-tributaria/cadastros/consultas/dados-publicos-cnpj) (acessado no dia 15/01/2022), é possível notar "umas inconsistências":
![minha-receita-ss-dtatualizacao](https://user-images.githubusercontent.com/5139459/149800757-8782ec76-dc74-472e-af2c-c8ef1bc62ca6.png)

- A data apontada pela seta vermelha, continua a mesma data do screenshot do @cuducos na abertura dessa issue;
- A data apontada pela seta azul, que parece ser a data de atualização correta, está "atrasada" com relação ao screenshot de abertura dessa issue, porém, ao olhar a data de atualização da página, gerada pelo CMS, vemos que a página foi atualizada no dia **14/01/2022**, o que pode indicar que o *08/01/2021* é um typo (deve ser **08/01/2022**), visto que a proposta do governo é de atualizar os arquivos mensalmente.

O **HTML** atual está "um pouco" diferente do **HTML** utilizado para os testes:

- No **HTML** de testes (lá na pasta `testdata`) não tem duas datas de atualização, só uma. O que também póde indicar ser um typo na página mais recente, já que tem diversos erros de  digitação nesta página, que estão sendo tratados no código;
- A estrutura em torno da informação da *Data da última extração:* difere "um pouquinho" da estrutura do **HTML** de testes. A minha sugestão seria pegar o elemento comum nos dois **HTML**s, que seria um `div` com id *#parent-fieldname-text* e parar na primeira ocorrência `"Data da última extração:"`. Não sei se atualizar o **HTML** de testes com a versão mais atual da página seria uma boa, já que, ao que tudo indica, o conteúdo dessa página não é lá muito confiável.

Sugestões?

**Comment by cuducos** [comment]
Cara, muita tosquice, mas enfim… não é a primeira. Temos que fazer _find & replace_ no código pq tem erros como `http//` (sem o `:`) no código.

> Sugestões?

1. Capturar a data mais recente: parece plausível que seja um erro na atualização, esqueceram de excluir a data antiga — pegar sempre a data mais nova das duas me parece ser melhor (inclusive semanticamente, se foi atualizado 2x, vale a mais nova).
2. Atualizar o HTML do `testdata` (talvez tenha que incluir manualmene algum _typo_ como `http//` para manter esses casos testados hehehe)

**Comment by cuducos** [comment]
Por sinal, protocolei um pedido de esclarecimento sobre isso no Fala.BR, protocolo 03005.021971/2022-55.

**Comment by cuducos** [comment]
Resposta do Ministério da Economia:

> Senhor(a),
> 
> O Serviço de Informações ao Cidadão do Ministério da Economia agradece o seu contato.
> 
> Em atenção à sua solicitação, informamos que:
> 
> 1 - A data de extração 14/01/22 se refere ao primeiro bloco de dados: Dados Abertos CNPJ EMPRESA 01 até Dados Abertos CNPJ SÓCIO 10.
> 
> 2 - As datas são distintas devido ao volume de informações extraídas. Se optou por dividir os dados em blocos, além de facilitar o download para o usuário.
> 
> 3 - A data de extração 08/01/22 se refere ao bloco de Informações sobre o Simples Nacional/MEI até Tabela de atributo qualificação dos sócios.
> 
> 4 - A data de extração 20/10/21 se refere bloco de dados do regime tributário das Pessoas Jurídicas.
> 
> Atenciosamente,
> Serviço de Informações ao Cidadão (SIC)
> Ministério da Economia

**Resumindo**, esse parágrafo cortado entre as setinhas vermelha e azul é a chave: a data depois dele é das informações que ele descreve, ou seja. _informações sobre o regime tributário das pessoas jurídicas_ ; ) 
![image](https://user-images.githubusercontent.com/4732915/151593744-72f0f990-0583-44a2-8282-2838fdd50e34.png)

Podemos adaptar a resposta para algo como:

```json
{
    "companies": "2021-12-12",
    "taxes": "2021-10-20"
}
```

**Comment by cuducos** [comment]
Pronto, o d2ba549 (que já está na _branch_ `main`) deve resolver isso ; )

**Comment by andidevel** [comment]
Olá @cuducos.

>     * (...) em PRs menores (talvez um apenas implementando a parte do comando `download` e criação do `last_update.txt`; (...)

Já tenho algum código para mostrar (com testes). Mas a branch `dev` não existe mais, faço a PR contra a `main` mesmo?

Estou fazendo o desenvolvimento aqui nesta [branch](https://github.com/andidevel/minha-receita/tree/feature-last-update/download).

**Comment by cuducos** [comment]
> Mas a branch `dev` não existe mais

Já foi mergeada na `main` — pode abrir para a `main` ; )

**Comment by andidevel** [comment]
Opa! Desculpem o sumiço... "meio" ocupado por aqui... Mas espero poder voltar a colaborar logo, logo (acho que o pior já passou, hehehe).

Claro, se ainda for necessário/possível.

Vou tentar seguir mais a risca as "guide lines" do projeto nas próximas contribuições. Já aprendi bastante com o pouco que contribui para o projeto no passado.

Valeu!
