### ISSUE TITLE
Checar se o comando `psql` está disponível antes de iniciar processamento

### ISSUE THREAD

**Issue by danielfireman** [cuducos/minha-receita#99]
Atualmente o erro aparece depois de um tempo de espera, e é:

```
Error: error saving companies: error saving companies: error while importing data to postgres : exec: "psql": executable file not found in $PATH
Usage:
  minha-receita transform [flags]

Flags:
  -b, --batch-size int                size of the batch to save to the database (default 8192)
  -c, --clean-up                      drop & recreate the database table before starting
  -u, --database-uri string           PostgreSQL URI (default POSTGRES_URI environment variable)
  -d, --directory string              directory of the downloaded CSV files (default "data")
  -h, --help                          help for transform
  -m, --max-parallel-db-queries int   maximum parallel database queries (default 32)
  -s, --postgres-schema string        PostgreSQL schema (default "public")

error saving companies: error saving companies: error while importing data to postgres : exec: "psql": executable file not found in $PATH
exit status 1
```

**Comment by athossampayo** [comment]
@danielfireman consegue detalhar mais sobre o erro para tentar reproduzir? Ele ocorre usando Docker ou com o build local? E tem alguma informação da instalação do psql? 

Aqui não consegui reproduzir usando tanto `go run main.go transform` nem com `minha-receita transform`. Minha instalação do psql foi usando o apt-get.

**Comment by cuducos** [comment]
> Ele ocorre usando Docker

Não, pq o [Docker tem PostgreSQL instalado](https://github.com/cuducos/minha-receita/blob/c04898214a0f1e8e4c323bbaca8ac65baf7ff405/Dockerfile#L16). Acontece em ambiente sem PostgreSQL instalado.

**Comment by cuducos** [comment]
> Minha instalação do psql foi usando o apt-get.

Se você desinstalar, aí deve ver o erro ; )

**Comment by athossampayo** [comment]
Agora entendi o problema, acreditava que no meio do processo algo deixava o comando indisponível. 

Vou dar uma olhada no código e de repente pego a issue, atualizo aqui se for o caso.

**Comment by cuducos** [comment]
> acreditava que no meio do processo algo deixava o comando indisponível.

Isso. A ideia é antes de começar a carregar os arquivos, já ocorra a verificação, assim quem utiliza tem uma resposta (um erro, no caso, com uma mensagem clara) mais rápido : )
